// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package sqlcgen

import (
	"context"
	"time"
)

const claimAttachment = `-- name: ClaimAttachment :one
UPDATE network_attachments SET lease_owner=$1::uuid,lease_until=clock_timestamp()+$2::bigint*interval '1 microsecond',epoch=epoch+1
WHERE tenant_id=$3 AND attachment_id=$4 RETURNING tenant_id, attachment_id, vpc_id, subnet_id, binding_id, instance_id, slot, request_key, submission_id, generation, fingerprint, cluster_id, namespace, binding_revision, plan, state, reason, protocol_blocked, version, pod_name, pod_uid, confirm_uid, finalization_id, provider_relations, created_at, updated_at, observed_at, released_at, next_check_at, lease_owner, lease_until, epoch, requested_generation, processed_generation, retry_not_before, evidence_hash, evidence_applied_at
`

type ClaimAttachmentParams struct {
	Owner        string
	LeaseMicros  int64
	TenantID     string
	AttachmentID string
}

func (q *Queries) ClaimAttachment(ctx context.Context, arg ClaimAttachmentParams) (NetworkAttachment, error) {
	row := q.db.QueryRow(ctx, claimAttachment,
		arg.Owner,
		arg.LeaseMicros,
		arg.TenantID,
		arg.AttachmentID,
	)
	var i NetworkAttachment
	err := row.Scan(
		&i.TenantID,
		&i.AttachmentID,
		&i.VpcID,
		&i.SubnetID,
		&i.BindingID,
		&i.InstanceID,
		&i.Slot,
		&i.RequestKey,
		&i.SubmissionID,
		&i.Generation,
		&i.Fingerprint,
		&i.ClusterID,
		&i.Namespace,
		&i.BindingRevision,
		&i.Plan,
		&i.State,
		&i.Reason,
		&i.ProtocolBlocked,
		&i.Version,
		&i.PodName,
		&i.PodUid,
		&i.ConfirmUid,
		&i.FinalizationID,
		&i.ProviderRelations,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.ReleasedAt,
		&i.NextCheckAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Epoch,
		&i.RequestedGeneration,
		&i.ProcessedGeneration,
		&i.RetryNotBefore,
		&i.EvidenceHash,
		&i.EvidenceAppliedAt,
	)
	return i, err
}

const confirmAttachment = `-- name: ConfirmAttachment :one
UPDATE network_attachments SET pod_name=$3,pod_uid=$4,confirm_uid=$4,version=version+1,updated_at=clock_timestamp(),next_check_at=clock_timestamp(),lease_owner=NULL,lease_until=NULL
WHERE tenant_id=$1 AND attachment_id=$2 RETURNING tenant_id, attachment_id, vpc_id, subnet_id, binding_id, instance_id, slot, request_key, submission_id, generation, fingerprint, cluster_id, namespace, binding_revision, plan, state, reason, protocol_blocked, version, pod_name, pod_uid, confirm_uid, finalization_id, provider_relations, created_at, updated_at, observed_at, released_at, next_check_at, lease_owner, lease_until, epoch, requested_generation, processed_generation, retry_not_before, evidence_hash, evidence_applied_at
`

type ConfirmAttachmentParams struct {
	TenantID     string
	AttachmentID string
	PodName      string
	PodUid       string
}

func (q *Queries) ConfirmAttachment(ctx context.Context, arg ConfirmAttachmentParams) (NetworkAttachment, error) {
	row := q.db.QueryRow(ctx, confirmAttachment,
		arg.TenantID,
		arg.AttachmentID,
		arg.PodName,
		arg.PodUid,
	)
	var i NetworkAttachment
	err := row.Scan(
		&i.TenantID,
		&i.AttachmentID,
		&i.VpcID,
		&i.SubnetID,
		&i.BindingID,
		&i.InstanceID,
		&i.Slot,
		&i.RequestKey,
		&i.SubmissionID,
		&i.Generation,
		&i.Fingerprint,
		&i.ClusterID,
		&i.Namespace,
		&i.BindingRevision,
		&i.Plan,
		&i.State,
		&i.Reason,
		&i.ProtocolBlocked,
		&i.Version,
		&i.PodName,
		&i.PodUid,
		&i.ConfirmUid,
		&i.FinalizationID,
		&i.ProviderRelations,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.ReleasedAt,
		&i.NextCheckAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Epoch,
		&i.RequestedGeneration,
		&i.ProcessedGeneration,
		&i.RetryNotBefore,
		&i.EvidenceHash,
		&i.EvidenceAppliedAt,
	)
	return i, err
}

const countAttachments = `-- name: CountAttachments :one
SELECT count(*)::bigint FROM network_attachments WHERE tenant_id=$1 AND subnet_id=$2 AND (state<>'released' OR protocol_blocked)
`

type CountAttachmentsParams struct {
	TenantID string
	SubnetID string
}

func (q *Queries) CountAttachments(ctx context.Context, arg CountAttachmentsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAttachments, arg.TenantID, arg.SubnetID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const finishAttachment = `-- name: FinishAttachment :one
UPDATE network_attachments SET state=$1,reason=$2,protocol_blocked=$3,pod_name=$4,pod_uid=$5,finalization_id=$6,
 provider_relations=$7,version=version+1,updated_at=clock_timestamp(),
 observed_at=CASE WHEN $8::boolean THEN $9::timestamptz ELSE observed_at END,
 released_at=CASE WHEN $1::text='released' THEN coalesce(released_at,clock_timestamp()) ELSE NULL END,
 processed_generation=greatest(processed_generation,$10::bigint),
 evidence_hash=CASE WHEN $8::boolean THEN $11::text ELSE evidence_hash END,
 evidence_applied_at=CASE WHEN $8::boolean THEN clock_timestamp() ELSE evidence_applied_at END,
 retry_not_before=CASE WHEN $12::boolean THEN clock_timestamp()+$13::bigint*interval '1 microsecond' ELSE '1970-01-01 UTC'::timestamptz END,
 next_check_at=CASE WHEN requested_generation>$10::bigint AND NOT $12::boolean THEN clock_timestamp() ELSE clock_timestamp()+$13::bigint*interval '1 microsecond' END,lease_owner=NULL,lease_until=NULL
WHERE tenant_id=$14 AND attachment_id=$15 AND version=$16 AND epoch=$17 AND lease_owner=$18::uuid AND lease_until>clock_timestamp() RETURNING tenant_id, attachment_id, vpc_id, subnet_id, binding_id, instance_id, slot, request_key, submission_id, generation, fingerprint, cluster_id, namespace, binding_revision, plan, state, reason, protocol_blocked, version, pod_name, pod_uid, confirm_uid, finalization_id, provider_relations, created_at, updated_at, observed_at, released_at, next_check_at, lease_owner, lease_until, epoch, requested_generation, processed_generation, retry_not_before, evidence_hash, evidence_applied_at
`

type FinishAttachmentParams struct {
	State             string
	Reason            string
	ProtocolBlocked   bool
	PodName           string
	PodUid            string
	FinalizationID    *string
	ProviderRelations []byte
	Observed          bool
	ObservedAt        *time.Time
	CoveredGeneration int64
	EvidenceHash      string
	Backoff           bool
	DelayMicros       int64
	TenantID          string
	AttachmentID      string
	Version           int64
	Epoch             int64
	Owner             string
}

func (q *Queries) FinishAttachment(ctx context.Context, arg FinishAttachmentParams) (NetworkAttachment, error) {
	row := q.db.QueryRow(ctx, finishAttachment,
		arg.State,
		arg.Reason,
		arg.ProtocolBlocked,
		arg.PodName,
		arg.PodUid,
		arg.FinalizationID,
		arg.ProviderRelations,
		arg.Observed,
		arg.ObservedAt,
		arg.CoveredGeneration,
		arg.EvidenceHash,
		arg.Backoff,
		arg.DelayMicros,
		arg.TenantID,
		arg.AttachmentID,
		arg.Version,
		arg.Epoch,
		arg.Owner,
	)
	var i NetworkAttachment
	err := row.Scan(
		&i.TenantID,
		&i.AttachmentID,
		&i.VpcID,
		&i.SubnetID,
		&i.BindingID,
		&i.InstanceID,
		&i.Slot,
		&i.RequestKey,
		&i.SubmissionID,
		&i.Generation,
		&i.Fingerprint,
		&i.ClusterID,
		&i.Namespace,
		&i.BindingRevision,
		&i.Plan,
		&i.State,
		&i.Reason,
		&i.ProtocolBlocked,
		&i.Version,
		&i.PodName,
		&i.PodUid,
		&i.ConfirmUid,
		&i.FinalizationID,
		&i.ProviderRelations,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.ReleasedAt,
		&i.NextCheckAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Epoch,
		&i.RequestedGeneration,
		&i.ProcessedGeneration,
		&i.RetryNotBefore,
		&i.EvidenceHash,
		&i.EvidenceAppliedAt,
	)
	return i, err
}

const getAttachment = `-- name: GetAttachment :one
SELECT tenant_id, attachment_id, vpc_id, subnet_id, binding_id, instance_id, slot, request_key, submission_id, generation, fingerprint, cluster_id, namespace, binding_revision, plan, state, reason, protocol_blocked, version, pod_name, pod_uid, confirm_uid, finalization_id, provider_relations, created_at, updated_at, observed_at, released_at, next_check_at, lease_owner, lease_until, epoch, requested_generation, processed_generation, retry_not_before, evidence_hash, evidence_applied_at FROM network_attachments WHERE tenant_id=$1 AND attachment_id=$2
`

type GetAttachmentParams struct {
	TenantID     string
	AttachmentID string
}

func (q *Queries) GetAttachment(ctx context.Context, arg GetAttachmentParams) (NetworkAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachment, arg.TenantID, arg.AttachmentID)
	var i NetworkAttachment
	err := row.Scan(
		&i.TenantID,
		&i.AttachmentID,
		&i.VpcID,
		&i.SubnetID,
		&i.BindingID,
		&i.InstanceID,
		&i.Slot,
		&i.RequestKey,
		&i.SubmissionID,
		&i.Generation,
		&i.Fingerprint,
		&i.ClusterID,
		&i.Namespace,
		&i.BindingRevision,
		&i.Plan,
		&i.State,
		&i.Reason,
		&i.ProtocolBlocked,
		&i.Version,
		&i.PodName,
		&i.PodUid,
		&i.ConfirmUid,
		&i.FinalizationID,
		&i.ProviderRelations,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.ReleasedAt,
		&i.NextCheckAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Epoch,
		&i.RequestedGeneration,
		&i.ProcessedGeneration,
		&i.RetryNotBefore,
		&i.EvidenceHash,
		&i.EvidenceAppliedAt,
	)
	return i, err
}

const getAttachmentReplay = `-- name: GetAttachmentReplay :one
SELECT tenant_id, attachment_id, vpc_id, subnet_id, binding_id, instance_id, slot, request_key, submission_id, generation, fingerprint, cluster_id, namespace, binding_revision, plan, state, reason, protocol_blocked, version, pod_name, pod_uid, confirm_uid, finalization_id, provider_relations, created_at, updated_at, observed_at, released_at, next_check_at, lease_owner, lease_until, epoch, requested_generation, processed_generation, retry_not_before, evidence_hash, evidence_applied_at FROM network_attachments WHERE tenant_id=$1 AND instance_id=$2 AND slot=$3 AND request_key=$4
`

type GetAttachmentReplayParams struct {
	TenantID   string
	InstanceID string
	Slot       string
	RequestKey string
}

func (q *Queries) GetAttachmentReplay(ctx context.Context, arg GetAttachmentReplayParams) (NetworkAttachment, error) {
	row := q.db.QueryRow(ctx, getAttachmentReplay,
		arg.TenantID,
		arg.InstanceID,
		arg.Slot,
		arg.RequestKey,
	)
	var i NetworkAttachment
	err := row.Scan(
		&i.TenantID,
		&i.AttachmentID,
		&i.VpcID,
		&i.SubnetID,
		&i.BindingID,
		&i.InstanceID,
		&i.Slot,
		&i.RequestKey,
		&i.SubmissionID,
		&i.Generation,
		&i.Fingerprint,
		&i.ClusterID,
		&i.Namespace,
		&i.BindingRevision,
		&i.Plan,
		&i.State,
		&i.Reason,
		&i.ProtocolBlocked,
		&i.Version,
		&i.PodName,
		&i.PodUid,
		&i.ConfirmUid,
		&i.FinalizationID,
		&i.ProviderRelations,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.ReleasedAt,
		&i.NextCheckAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Epoch,
		&i.RequestedGeneration,
		&i.ProcessedGeneration,
		&i.RetryNotBefore,
		&i.EvidenceHash,
		&i.EvidenceAppliedAt,
	)
	return i, err
}

const hasAttachmentSlot = `-- name: HasAttachmentSlot :one
SELECT EXISTS(SELECT 1 FROM network_attachments WHERE tenant_id=$1 AND instance_id=$2 AND slot=$3 AND (state<>'released' OR protocol_blocked))
`

type HasAttachmentSlotParams struct {
	TenantID   string
	InstanceID string
	Slot       string
}

func (q *Queries) HasAttachmentSlot(ctx context.Context, arg HasAttachmentSlotParams) (bool, error) {
	row := q.db.QueryRow(ctx, hasAttachmentSlot, arg.TenantID, arg.InstanceID, arg.Slot)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertAttachment = `-- name: InsertAttachment :one
INSERT INTO network_attachments(tenant_id,attachment_id,vpc_id,subnet_id,binding_id,instance_id,slot,request_key,submission_id,generation,fingerprint,cluster_id,namespace,binding_revision,plan,state)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,'reserved') RETURNING tenant_id, attachment_id, vpc_id, subnet_id, binding_id, instance_id, slot, request_key, submission_id, generation, fingerprint, cluster_id, namespace, binding_revision, plan, state, reason, protocol_blocked, version, pod_name, pod_uid, confirm_uid, finalization_id, provider_relations, created_at, updated_at, observed_at, released_at, next_check_at, lease_owner, lease_until, epoch, requested_generation, processed_generation, retry_not_before, evidence_hash, evidence_applied_at
`

type InsertAttachmentParams struct {
	TenantID        string
	AttachmentID    string
	VpcID           string
	SubnetID        string
	BindingID       string
	InstanceID      string
	Slot            string
	RequestKey      string
	SubmissionID    string
	Generation      int64
	Fingerprint     string
	ClusterID       string
	Namespace       string
	BindingRevision string
	Plan            []byte
}

func (q *Queries) InsertAttachment(ctx context.Context, arg InsertAttachmentParams) (NetworkAttachment, error) {
	row := q.db.QueryRow(ctx, insertAttachment,
		arg.TenantID,
		arg.AttachmentID,
		arg.VpcID,
		arg.SubnetID,
		arg.BindingID,
		arg.InstanceID,
		arg.Slot,
		arg.RequestKey,
		arg.SubmissionID,
		arg.Generation,
		arg.Fingerprint,
		arg.ClusterID,
		arg.Namespace,
		arg.BindingRevision,
		arg.Plan,
	)
	var i NetworkAttachment
	err := row.Scan(
		&i.TenantID,
		&i.AttachmentID,
		&i.VpcID,
		&i.SubnetID,
		&i.BindingID,
		&i.InstanceID,
		&i.Slot,
		&i.RequestKey,
		&i.SubmissionID,
		&i.Generation,
		&i.Fingerprint,
		&i.ClusterID,
		&i.Namespace,
		&i.BindingRevision,
		&i.Plan,
		&i.State,
		&i.Reason,
		&i.ProtocolBlocked,
		&i.Version,
		&i.PodName,
		&i.PodUid,
		&i.ConfirmUid,
		&i.FinalizationID,
		&i.ProviderRelations,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.ReleasedAt,
		&i.NextCheckAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Epoch,
		&i.RequestedGeneration,
		&i.ProcessedGeneration,
		&i.RetryNotBefore,
		&i.EvidenceHash,
		&i.EvidenceAppliedAt,
	)
	return i, err
}

const insertAttachmentHistory = `-- name: InsertAttachmentHistory :exec
INSERT INTO network_attachment_history(tenant_id,history_id,attachment_id,version,event,state,reason,pod_uid,finalization_id)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type InsertAttachmentHistoryParams struct {
	TenantID       string
	HistoryID      string
	AttachmentID   string
	Version        int64
	Event          string
	State          string
	Reason         string
	PodUid         string
	FinalizationID *string
}

func (q *Queries) InsertAttachmentHistory(ctx context.Context, arg InsertAttachmentHistoryParams) error {
	_, err := q.db.Exec(ctx, insertAttachmentHistory,
		arg.TenantID,
		arg.HistoryID,
		arg.AttachmentID,
		arg.Version,
		arg.Event,
		arg.State,
		arg.Reason,
		arg.PodUid,
		arg.FinalizationID,
	)
	return err
}

const lockAttachment = `-- name: LockAttachment :one
SELECT tenant_id, attachment_id, vpc_id, subnet_id, binding_id, instance_id, slot, request_key, submission_id, generation, fingerprint, cluster_id, namespace, binding_revision, plan, state, reason, protocol_blocked, version, pod_name, pod_uid, confirm_uid, finalization_id, provider_relations, created_at, updated_at, observed_at, released_at, next_check_at, lease_owner, lease_until, epoch, requested_generation, processed_generation, retry_not_before, evidence_hash, evidence_applied_at FROM network_attachments WHERE tenant_id=$1 AND attachment_id=$2 FOR UPDATE
`

type LockAttachmentParams struct {
	TenantID     string
	AttachmentID string
}

func (q *Queries) LockAttachment(ctx context.Context, arg LockAttachmentParams) (NetworkAttachment, error) {
	row := q.db.QueryRow(ctx, lockAttachment, arg.TenantID, arg.AttachmentID)
	var i NetworkAttachment
	err := row.Scan(
		&i.TenantID,
		&i.AttachmentID,
		&i.VpcID,
		&i.SubnetID,
		&i.BindingID,
		&i.InstanceID,
		&i.Slot,
		&i.RequestKey,
		&i.SubmissionID,
		&i.Generation,
		&i.Fingerprint,
		&i.ClusterID,
		&i.Namespace,
		&i.BindingRevision,
		&i.Plan,
		&i.State,
		&i.Reason,
		&i.ProtocolBlocked,
		&i.Version,
		&i.PodName,
		&i.PodUid,
		&i.ConfirmUid,
		&i.FinalizationID,
		&i.ProviderRelations,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.ReleasedAt,
		&i.NextCheckAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Epoch,
		&i.RequestedGeneration,
		&i.ProcessedGeneration,
		&i.RetryNotBefore,
		&i.EvidenceHash,
		&i.EvidenceAppliedAt,
	)
	return i, err
}

const lockAttachmentSlot = `-- name: LockAttachmentSlot :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text||':attachment:'||$2::text||':'||$3::text,0))
`

type LockAttachmentSlotParams struct {
	TenantID   string
	InstanceID string
	Slot       string
}

func (q *Queries) LockAttachmentSlot(ctx context.Context, arg LockAttachmentSlotParams) error {
	_, err := q.db.Exec(ctx, lockAttachmentSlot, arg.TenantID, arg.InstanceID, arg.Slot)
	return err
}

const lockDueAttachment = `-- name: LockDueAttachment :one
SELECT tenant_id, attachment_id, vpc_id, subnet_id, binding_id, instance_id, slot, request_key, submission_id, generation, fingerprint, cluster_id, namespace, binding_revision, plan, state, reason, protocol_blocked, version, pod_name, pod_uid, confirm_uid, finalization_id, provider_relations, created_at, updated_at, observed_at, released_at, next_check_at, lease_owner, lease_until, epoch, requested_generation, processed_generation, retry_not_before, evidence_hash, evidence_applied_at FROM network_attachments WHERE tenant_id=$1 AND subnet_id=$2 AND next_check_at<=clock_timestamp() AND (lease_until IS NULL OR lease_until<=clock_timestamp())
ORDER BY next_check_at,attachment_id LIMIT 1 FOR UPDATE SKIP LOCKED
`

type LockDueAttachmentParams struct {
	TenantID string
	SubnetID string
}

func (q *Queries) LockDueAttachment(ctx context.Context, arg LockDueAttachmentParams) (NetworkAttachment, error) {
	row := q.db.QueryRow(ctx, lockDueAttachment, arg.TenantID, arg.SubnetID)
	var i NetworkAttachment
	err := row.Scan(
		&i.TenantID,
		&i.AttachmentID,
		&i.VpcID,
		&i.SubnetID,
		&i.BindingID,
		&i.InstanceID,
		&i.Slot,
		&i.RequestKey,
		&i.SubmissionID,
		&i.Generation,
		&i.Fingerprint,
		&i.ClusterID,
		&i.Namespace,
		&i.BindingRevision,
		&i.Plan,
		&i.State,
		&i.Reason,
		&i.ProtocolBlocked,
		&i.Version,
		&i.PodName,
		&i.PodUid,
		&i.ConfirmUid,
		&i.FinalizationID,
		&i.ProviderRelations,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.ReleasedAt,
		&i.NextCheckAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Epoch,
		&i.RequestedGeneration,
		&i.ProcessedGeneration,
		&i.RetryNotBefore,
		&i.EvidenceHash,
		&i.EvidenceAppliedAt,
	)
	return i, err
}

const lockDueAttachmentParent = `-- name: LockDueAttachmentParent :one
SELECT v.tenant_id, v.vpc_id, v.name, v.description, v.cidr, v.state, v.reason, v.version, v.created_at, v.updated_at, v.observed_at, v.last_operation_id, v.base_connectivity_required FROM network_vpcs v WHERE EXISTS(SELECT 1 FROM network_attachments a WHERE a.tenant_id=v.tenant_id AND a.vpc_id=v.vpc_id AND a.next_check_at<=clock_timestamp() AND (a.lease_until IS NULL OR a.lease_until<=clock_timestamp()))
ORDER BY (SELECT min(a.next_check_at) FROM network_attachments a WHERE a.tenant_id=v.tenant_id AND a.vpc_id=v.vpc_id AND (a.lease_until IS NULL OR a.lease_until<=clock_timestamp())),v.vpc_id LIMIT 1 FOR UPDATE OF v SKIP LOCKED
`

func (q *Queries) LockDueAttachmentParent(ctx context.Context) (NetworkVpc, error) {
	row := q.db.QueryRow(ctx, lockDueAttachmentParent)
	var i NetworkVpc
	err := row.Scan(
		&i.TenantID,
		&i.VpcID,
		&i.Name,
		&i.Description,
		&i.Cidr,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.BaseConnectivityRequired,
	)
	return i, err
}

const lockDueAttachmentSubnet = `-- name: LockDueAttachmentSubnet :one
SELECT s.tenant_id, s.subnet_id, s.vpc_id, s.name, s.description, s.cidr, s.gateway, s.state, s.reason, s.version, s.created_at, s.updated_at, s.observed_at, s.last_operation_id FROM network_subnets s WHERE s.tenant_id=$1 AND s.vpc_id=$2 AND EXISTS(SELECT 1 FROM network_attachments a WHERE a.tenant_id=s.tenant_id AND a.subnet_id=s.subnet_id AND a.next_check_at<=clock_timestamp() AND (a.lease_until IS NULL OR a.lease_until<=clock_timestamp()))
ORDER BY (SELECT min(a.next_check_at) FROM network_attachments a WHERE a.tenant_id=s.tenant_id AND a.subnet_id=s.subnet_id AND (a.lease_until IS NULL OR a.lease_until<=clock_timestamp())),s.subnet_id LIMIT 1 FOR UPDATE OF s SKIP LOCKED
`

type LockDueAttachmentSubnetParams struct {
	TenantID string
	VpcID    string
}

func (q *Queries) LockDueAttachmentSubnet(ctx context.Context, arg LockDueAttachmentSubnetParams) (NetworkSubnet, error) {
	row := q.db.QueryRow(ctx, lockDueAttachmentSubnet, arg.TenantID, arg.VpcID)
	var i NetworkSubnet
	err := row.Scan(
		&i.TenantID,
		&i.SubnetID,
		&i.VpcID,
		&i.Name,
		&i.Description,
		&i.Cidr,
		&i.Gateway,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
	)
	return i, err
}

const releaseAttachment = `-- name: ReleaseAttachment :one
UPDATE network_attachments SET finalization_id=$3,state='releasing',version=version+1,updated_at=clock_timestamp(),next_check_at=clock_timestamp(),lease_owner=NULL,lease_until=NULL
WHERE tenant_id=$1 AND attachment_id=$2 RETURNING tenant_id, attachment_id, vpc_id, subnet_id, binding_id, instance_id, slot, request_key, submission_id, generation, fingerprint, cluster_id, namespace, binding_revision, plan, state, reason, protocol_blocked, version, pod_name, pod_uid, confirm_uid, finalization_id, provider_relations, created_at, updated_at, observed_at, released_at, next_check_at, lease_owner, lease_until, epoch, requested_generation, processed_generation, retry_not_before, evidence_hash, evidence_applied_at
`

type ReleaseAttachmentParams struct {
	TenantID       string
	AttachmentID   string
	FinalizationID *string
}

func (q *Queries) ReleaseAttachment(ctx context.Context, arg ReleaseAttachmentParams) (NetworkAttachment, error) {
	row := q.db.QueryRow(ctx, releaseAttachment, arg.TenantID, arg.AttachmentID, arg.FinalizationID)
	var i NetworkAttachment
	err := row.Scan(
		&i.TenantID,
		&i.AttachmentID,
		&i.VpcID,
		&i.SubnetID,
		&i.BindingID,
		&i.InstanceID,
		&i.Slot,
		&i.RequestKey,
		&i.SubmissionID,
		&i.Generation,
		&i.Fingerprint,
		&i.ClusterID,
		&i.Namespace,
		&i.BindingRevision,
		&i.Plan,
		&i.State,
		&i.Reason,
		&i.ProtocolBlocked,
		&i.Version,
		&i.PodName,
		&i.PodUid,
		&i.ConfirmUid,
		&i.FinalizationID,
		&i.ProviderRelations,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.ReleasedAt,
		&i.NextCheckAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.Epoch,
		&i.RequestedGeneration,
		&i.ProcessedGeneration,
		&i.RetryNotBefore,
		&i.EvidenceHash,
		&i.EvidenceAppliedAt,
	)
	return i, err
}
