// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: base_backfill.sql

package sqlcgen

import (
	"context"
)

const activateLegacyBaseAggregation = `-- name: ActivateLegacyBaseAggregation :execrows
UPDATE network_connectivity_rollout SET legacy_aggregation_enabled=true,updated_at=clock_timestamp()
WHERE cluster_id=$1 AND new_vpcs_enabled
`

type ActivateLegacyBaseAggregationParams struct {
	ClusterID string
}

func (q *Queries) ActivateLegacyBaseAggregation(ctx context.Context, arg ActivateLegacyBaseAggregationParams) (int64, error) {
	result, err := q.db.Exec(ctx, activateLegacyBaseAggregation, arg.ClusterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const admitBaseBackfillVPC = `-- name: AdmitBaseBackfillVPC :execrows
UPDATE network_vpcs SET last_operation_id=$1,version=version+1,updated_at=clock_timestamp()
WHERE tenant_id=$2 AND vpc_id=$3 AND version=$4
 AND state IN ('available','degraded') AND NOT base_connectivity_required
`

type AdmitBaseBackfillVPCParams struct {
	OperationID string
	TenantID    string
	VpcID       string
	Version     int64
}

func (q *Queries) AdmitBaseBackfillVPC(ctx context.Context, arg AdmitBaseBackfillVPCParams) (int64, error) {
	result, err := q.db.Exec(ctx, admitBaseBackfillVPC,
		arg.OperationID,
		arg.TenantID,
		arg.VpcID,
		arg.Version,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const advanceBaseBackfillAdmission = `-- name: AdvanceBaseBackfillAdmission :execrows
UPDATE network_base_backfill_runs
SET next_admission_at=clock_timestamp()+interval_ms*interval '1 millisecond',
 paused=paused OR $1::boolean
WHERE run_id=$2 AND cluster_id=$3
`

type AdvanceBaseBackfillAdmissionParams struct {
	Blocked   bool
	RunID     string
	ClusterID string
}

func (q *Queries) AdvanceBaseBackfillAdmission(ctx context.Context, arg AdvanceBaseBackfillAdmissionParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceBaseBackfillAdmission, arg.Blocked, arg.RunID, arg.ClusterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countStaleLegacyBaseEvidence = `-- name: CountStaleLegacyBaseEvidence :one
SELECT count(*)::bigint FROM network_vpcs v
JOIN network_tenant_namespaces ns ON ns.tenant_id=v.tenant_id AND ns.cluster_id=$1
LEFT JOIN network_provider_bindings placement ON placement.tenant_id=v.tenant_id AND placement.vpc_id=v.vpc_id
LEFT JOIN network_vpc_base_connectivity b ON b.tenant_id=v.tenant_id AND b.vpc_id=v.vpc_id
LEFT JOIN network_eips e ON e.tenant_id=b.tenant_id AND e.eip_id=b.eip_id
LEFT JOIN network_snat_bindings s ON s.tenant_id=b.tenant_id AND s.snat_id=b.snat_id
WHERE (placement.cluster_id=$1 OR placement.binding_id IS NULL)
 AND v.state NOT IN ('deleting','deleted')
 AND (b.observed_at IS NULL OR b.provider_observed_at IS NULL OR e.observed_at IS NULL OR s.observed_at IS NULL
 OR least(b.observed_at,b.provider_observed_at,e.observed_at,s.observed_at)<clock_timestamp()-$2::bigint*interval '1 microsecond'
 OR greatest(b.observed_at,b.provider_observed_at,e.observed_at,s.observed_at)>clock_timestamp())
`

type CountStaleLegacyBaseEvidenceParams struct {
	ClusterID       string
	FreshnessMicros int64
}

// Recheck wall-clock freshness after the per-resource verification loop. A long
// activation cannot accept facts that expired while earlier VPC rows were locked.
func (q *Queries) CountStaleLegacyBaseEvidence(ctx context.Context, arg CountStaleLegacyBaseEvidenceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countStaleLegacyBaseEvidence, arg.ClusterID, arg.FreshnessMicros)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const ensureConnectivityRollout = `-- name: EnsureConnectivityRollout :exec
INSERT INTO network_connectivity_rollout(cluster_id) VALUES($1) ON CONFLICT DO NOTHING
`

type EnsureConnectivityRolloutParams struct {
	ClusterID string
}

func (q *Queries) EnsureConnectivityRollout(ctx context.Context, arg EnsureConnectivityRolloutParams) error {
	_, err := q.db.Exec(ctx, ensureConnectivityRollout, arg.ClusterID)
	return err
}

const getBaseBackfillRun = `-- name: GetBaseBackfillRun :one
SELECT run_id, cluster_id, pool_id, pool_revision, scope, paused, interval_ms, next_admission_at, created_at, plan_sha256, reviewed_at FROM network_base_backfill_runs WHERE run_id=$1 AND cluster_id=$2
`

type GetBaseBackfillRunParams struct {
	RunID     string
	ClusterID string
}

func (q *Queries) GetBaseBackfillRun(ctx context.Context, arg GetBaseBackfillRunParams) (NetworkBaseBackfillRun, error) {
	row := q.db.QueryRow(ctx, getBaseBackfillRun, arg.RunID, arg.ClusterID)
	var i NetworkBaseBackfillRun
	err := row.Scan(
		&i.RunID,
		&i.ClusterID,
		&i.PoolID,
		&i.PoolRevision,
		&i.Scope,
		&i.Paused,
		&i.IntervalMs,
		&i.NextAdmissionAt,
		&i.CreatedAt,
		&i.PlanSha256,
		&i.ReviewedAt,
	)
	return i, err
}

const insertBaseBackfillCandidate = `-- name: InsertBaseBackfillCandidate :exec
INSERT INTO network_base_backfill_candidates
(tenant_id,run_id,cluster_id,vpc_id,accepted_vpc_version,namespace,binding_id,provider_name,provider_uid,initial_state,initial_reason,state,reason)
VALUES($1,$2,$3,$4,$5,
 $6,$7,$8,$9,
 $10,$11,$10,$11)
`

type InsertBaseBackfillCandidateParams struct {
	TenantID           string
	RunID              string
	ClusterID          string
	VpcID              string
	AcceptedVpcVersion int64
	Namespace          *string
	BindingID          *string
	ProviderName       string
	ProviderUid        string
	InitialState       string
	InitialReason      string
}

func (q *Queries) InsertBaseBackfillCandidate(ctx context.Context, arg InsertBaseBackfillCandidateParams) error {
	_, err := q.db.Exec(ctx, insertBaseBackfillCandidate,
		arg.TenantID,
		arg.RunID,
		arg.ClusterID,
		arg.VpcID,
		arg.AcceptedVpcVersion,
		arg.Namespace,
		arg.BindingID,
		arg.ProviderName,
		arg.ProviderUid,
		arg.InitialState,
		arg.InitialReason,
	)
	return err
}

const insertBaseBackfillRun = `-- name: InsertBaseBackfillRun :exec
INSERT INTO network_base_backfill_runs(run_id,cluster_id,pool_id,pool_revision,interval_ms,plan_sha256)
VALUES($1,$2,$3,$4,$5,$6)
`

type InsertBaseBackfillRunParams struct {
	RunID        string
	ClusterID    string
	PoolID       string
	PoolRevision int64
	IntervalMs   int64
	PlanSha256   string
}

func (q *Queries) InsertBaseBackfillRun(ctx context.Context, arg InsertBaseBackfillRunParams) error {
	_, err := q.db.Exec(ctx, insertBaseBackfillRun,
		arg.RunID,
		arg.ClusterID,
		arg.PoolID,
		arg.PoolRevision,
		arg.IntervalMs,
		arg.PlanSha256,
	)
	return err
}

const listBaseBackfillCandidates = `-- name: ListBaseBackfillCandidates :many
SELECT c.tenant_id, c.run_id, c.cluster_id, c.vpc_id, c.accepted_vpc_version, c.state, c.reason, c.operation_id, c.namespace, c.binding_id, c.provider_name, c.provider_uid, c.initial_state, c.initial_reason,coalesce(o.state,'')::text AS operation_state,coalesce(b.state,'missing')::text AS base_state
FROM network_base_backfill_candidates c
LEFT JOIN network_operations o ON o.tenant_id=c.tenant_id AND o.operation_id=c.operation_id
LEFT JOIN network_vpc_base_connectivity b ON b.tenant_id=c.tenant_id AND b.vpc_id=c.vpc_id
WHERE c.run_id=$1 AND c.cluster_id=$2 ORDER BY c.tenant_id,c.vpc_id
`

type ListBaseBackfillCandidatesParams struct {
	RunID     string
	ClusterID string
}

type ListBaseBackfillCandidatesRow struct {
	TenantID           string
	RunID              string
	ClusterID          string
	VpcID              string
	AcceptedVpcVersion int64
	State              string
	Reason             string
	OperationID        *string
	Namespace          *string
	BindingID          *string
	ProviderName       string
	ProviderUid        string
	InitialState       string
	InitialReason      string
	OperationState     string
	BaseState          string
}

// Read-only evidence includes live execution facts without rewriting the reviewed
// candidate snapshot. The run is platform metadata; candidate joins preserve tenant.
func (q *Queries) ListBaseBackfillCandidates(ctx context.Context, arg ListBaseBackfillCandidatesParams) ([]ListBaseBackfillCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listBaseBackfillCandidates, arg.RunID, arg.ClusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBaseBackfillCandidatesRow{}
	for rows.Next() {
		var i ListBaseBackfillCandidatesRow
		if err := rows.Scan(
			&i.TenantID,
			&i.RunID,
			&i.ClusterID,
			&i.VpcID,
			&i.AcceptedVpcVersion,
			&i.State,
			&i.Reason,
			&i.OperationID,
			&i.Namespace,
			&i.BindingID,
			&i.ProviderName,
			&i.ProviderUid,
			&i.InitialState,
			&i.InitialReason,
			&i.OperationState,
			&i.BaseState,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBaseBackfillInventory = `-- name: ListBaseBackfillInventory :many
SELECT v.tenant_id,v.vpc_id,v.version,v.state,
 b.binding_id,b.namespace,coalesce(b.provider_name,'')::text AS provider_name,
 coalesce(b.provider_uid,'')::text AS provider_uid,coalesce(b.pending_action,'')::text AS pending_action,
 coalesce(o.state,'')::text AS operation_state,
 (bc.vpc_id IS NOT NULL)::boolean AS has_base
FROM network_vpcs v
JOIN network_tenant_namespaces ns ON ns.tenant_id=v.tenant_id AND ns.cluster_id=$1
LEFT JOIN network_provider_bindings b ON b.tenant_id=v.tenant_id AND b.vpc_id=v.vpc_id
LEFT JOIN network_operations o ON o.tenant_id=v.tenant_id AND o.operation_id=v.last_operation_id
LEFT JOIN network_vpc_base_connectivity bc ON bc.tenant_id=v.tenant_id AND bc.vpc_id=v.vpc_id
WHERE b.cluster_id=$1 OR b.binding_id IS NULL
ORDER BY v.tenant_id,v.vpc_id LIMIT $2::integer
`

type ListBaseBackfillInventoryParams struct {
	ClusterID  string
	MaxResults int32
}

type ListBaseBackfillInventoryRow struct {
	TenantID       string
	VpcID          string
	Version        int64
	State          string
	BindingID      *string
	Namespace      *string
	ProviderName   string
	ProviderUid    string
	PendingAction  string
	OperationState string
	HasBase        bool
}

// Administrative cross-tenant inventory, bounded to the explicit cluster. Every
// candidate retains its tenant and subsequent mutations use that tenant scope.
func (q *Queries) ListBaseBackfillInventory(ctx context.Context, arg ListBaseBackfillInventoryParams) ([]ListBaseBackfillInventoryRow, error) {
	rows, err := q.db.Query(ctx, listBaseBackfillInventory, arg.ClusterID, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBaseBackfillInventoryRow{}
	for rows.Next() {
		var i ListBaseBackfillInventoryRow
		if err := rows.Scan(
			&i.TenantID,
			&i.VpcID,
			&i.Version,
			&i.State,
			&i.BindingID,
			&i.Namespace,
			&i.ProviderName,
			&i.ProviderUid,
			&i.PendingAction,
			&i.OperationState,
			&i.HasBase,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockBaseBackfillPlanKey = `-- name: LockBaseBackfillPlanKey :exec
SELECT pg_advisory_xact_lock(hashtextextended('base-backfill-plan:'||$1::text,0))
`

type LockBaseBackfillPlanKeyParams struct {
	RunID string
}

func (q *Queries) LockBaseBackfillPlanKey(ctx context.Context, arg LockBaseBackfillPlanKeyParams) error {
	_, err := q.db.Exec(ctx, lockBaseBackfillPlanKey, arg.RunID)
	return err
}

const lockBaseBackfillRun = `-- name: LockBaseBackfillRun :one
SELECT run_id, cluster_id, pool_id, pool_revision, scope, paused, interval_ms, next_admission_at, created_at, plan_sha256, reviewed_at FROM network_base_backfill_runs WHERE run_id=$1 AND cluster_id=$2 FOR UPDATE
`

type LockBaseBackfillRunParams struct {
	RunID     string
	ClusterID string
}

func (q *Queries) LockBaseBackfillRun(ctx context.Context, arg LockBaseBackfillRunParams) (NetworkBaseBackfillRun, error) {
	row := q.db.QueryRow(ctx, lockBaseBackfillRun, arg.RunID, arg.ClusterID)
	var i NetworkBaseBackfillRun
	err := row.Scan(
		&i.RunID,
		&i.ClusterID,
		&i.PoolID,
		&i.PoolRevision,
		&i.Scope,
		&i.Paused,
		&i.IntervalMs,
		&i.NextAdmissionAt,
		&i.CreatedAt,
		&i.PlanSha256,
		&i.ReviewedAt,
	)
	return i, err
}

const lockConnectivityRollout = `-- name: LockConnectivityRollout :exec
SELECT pg_advisory_xact_lock(hashtextextended('connectivity-rollout:'||$1::text,0))
`

type LockConnectivityRolloutParams struct {
	ClusterID string
}

// Shared with first VPC admission, including the missing rollout-row case.
func (q *Queries) LockConnectivityRollout(ctx context.Context, arg LockConnectivityRolloutParams) error {
	_, err := q.db.Exec(ctx, lockConnectivityRollout, arg.ClusterID)
	return err
}

const lockLegacyBaseAggregationVPCs = `-- name: LockLegacyBaseAggregationVPCs :many
SELECT v.tenant_id,v.vpc_id,v.base_connectivity_required
FROM network_vpcs v
JOIN network_tenant_namespaces ns ON ns.tenant_id=v.tenant_id AND ns.cluster_id=$1
LEFT JOIN network_provider_bindings b ON b.tenant_id=v.tenant_id AND b.vpc_id=v.vpc_id
WHERE (b.cluster_id=$1 OR b.binding_id IS NULL) AND v.state NOT IN ('deleting','deleted')
ORDER BY v.tenant_id,v.vpc_id FOR UPDATE OF v
`

type LockLegacyBaseAggregationVPCsParams struct {
	ClusterID string
}

type LockLegacyBaseAggregationVPCsRow struct {
	TenantID                 string
	VpcID                    string
	BaseConnectivityRequired bool
}

// The exclusive rollout lock closes concurrent admission while all legacy rows
// are held in deterministic order. No Provider call is made under these locks.
func (q *Queries) LockLegacyBaseAggregationVPCs(ctx context.Context, arg LockLegacyBaseAggregationVPCsParams) ([]LockLegacyBaseAggregationVPCsRow, error) {
	rows, err := q.db.Query(ctx, lockLegacyBaseAggregationVPCs, arg.ClusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LockLegacyBaseAggregationVPCsRow{}
	for rows.Next() {
		var i LockLegacyBaseAggregationVPCsRow
		if err := rows.Scan(&i.TenantID, &i.VpcID, &i.BaseConnectivityRequired); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextBaseBackfillCandidate = `-- name: NextBaseBackfillCandidate :one
SELECT tenant_id, run_id, cluster_id, vpc_id, accepted_vpc_version, state, reason, operation_id, namespace, binding_id, provider_name, provider_uid, initial_state, initial_reason FROM network_base_backfill_candidates
WHERE run_id=$1 AND cluster_id=$2 AND state='pending'
ORDER BY tenant_id,vpc_id LIMIT 1
`

type NextBaseBackfillCandidateParams struct {
	RunID     string
	ClusterID string
}

func (q *Queries) NextBaseBackfillCandidate(ctx context.Context, arg NextBaseBackfillCandidateParams) (NetworkBaseBackfillCandidate, error) {
	row := q.db.QueryRow(ctx, nextBaseBackfillCandidate, arg.RunID, arg.ClusterID)
	var i NetworkBaseBackfillCandidate
	err := row.Scan(
		&i.TenantID,
		&i.RunID,
		&i.ClusterID,
		&i.VpcID,
		&i.AcceptedVpcVersion,
		&i.State,
		&i.Reason,
		&i.OperationID,
		&i.Namespace,
		&i.BindingID,
		&i.ProviderName,
		&i.ProviderUid,
		&i.InitialState,
		&i.InitialReason,
	)
	return i, err
}

const scheduleBaseBackfill = `-- name: ScheduleBaseBackfill :execrows
UPDATE network_reconciliations SET next_run_at=clock_timestamp(),lease_owner=NULL,
 lease_until=NULL,lease_epoch=lease_epoch+1,requested_generation=requested_generation+1
WHERE tenant_id=$1 AND vpc_id=$2
`

type ScheduleBaseBackfillParams struct {
	TenantID string
	VpcID    *string
}

func (q *Queries) ScheduleBaseBackfill(ctx context.Context, arg ScheduleBaseBackfillParams) (int64, error) {
	result, err := q.db.Exec(ctx, scheduleBaseBackfill, arg.TenantID, arg.VpcID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBaseBackfillCandidateResult = `-- name: SetBaseBackfillCandidateResult :execrows
UPDATE network_base_backfill_candidates
SET state=$1,reason=$2,operation_id=$3
WHERE tenant_id=$4 AND run_id=$5 AND vpc_id=$6 AND state='pending'
`

type SetBaseBackfillCandidateResultParams struct {
	State       string
	Reason      string
	OperationID *string
	TenantID    string
	RunID       string
	VpcID       string
}

func (q *Queries) SetBaseBackfillCandidateResult(ctx context.Context, arg SetBaseBackfillCandidateResultParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBaseBackfillCandidateResult,
		arg.State,
		arg.Reason,
		arg.OperationID,
		arg.TenantID,
		arg.RunID,
		arg.VpcID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBaseBackfillPaused = `-- name: SetBaseBackfillPaused :execrows
UPDATE network_base_backfill_runs SET paused=$1,
 reviewed_at=CASE WHEN NOT $1::boolean THEN clock_timestamp() ELSE reviewed_at END
WHERE run_id=$2 AND cluster_id=$3
 AND ($1::boolean OR plan_sha256=$4)
`

type SetBaseBackfillPausedParams struct {
	Paused         bool
	RunID          string
	ClusterID      string
	ReviewedSha256 string
}

func (q *Queries) SetBaseBackfillPaused(ctx context.Context, arg SetBaseBackfillPausedParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBaseBackfillPaused,
		arg.Paused,
		arg.RunID,
		arg.ClusterID,
		arg.ReviewedSha256,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setNewVPCConnectivityEnabled = `-- name: SetNewVPCConnectivityEnabled :execrows
UPDATE network_connectivity_rollout SET new_vpcs_enabled=$1,updated_at=clock_timestamp()
WHERE cluster_id=$2 AND ($1::boolean OR NOT legacy_aggregation_enabled)
`

type SetNewVPCConnectivityEnabledParams struct {
	Enabled   bool
	ClusterID string
}

func (q *Queries) SetNewVPCConnectivityEnabled(ctx context.Context, arg SetNewVPCConnectivityEnabledParams) (int64, error) {
	result, err := q.db.Exec(ctx, setNewVPCConnectivityEnabled, arg.Enabled, arg.ClusterID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
