// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: base_connectivity.sql

package sqlcgen

import (
	"context"
	"time"
)

const blockingLBForSubnet = `-- name: BlockingLBForSubnet :one
SELECT count(*)::bigint FROM network_load_balancers WHERE tenant_id=$1 AND subnet_id=$2 AND state<>'deleted'
`

type BlockingLBForSubnetParams struct {
	TenantID string
	SubnetID string
}

func (q *Queries) BlockingLBForSubnet(ctx context.Context, arg BlockingLBForSubnetParams) (int64, error) {
	row := q.db.QueryRow(ctx, blockingLBForSubnet, arg.TenantID, arg.SubnetID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const blockingLBForVPC = `-- name: BlockingLBForVPC :one
SELECT count(*)::bigint FROM network_load_balancers WHERE tenant_id=$1 AND vpc_id=$2 AND state<>'deleted'
`

type BlockingLBForVPCParams struct {
	TenantID string
	VpcID    string
}

func (q *Queries) BlockingLBForVPC(ctx context.Context, arg BlockingLBForVPCParams) (int64, error) {
	row := q.db.QueryRow(ctx, blockingLBForVPC, arg.TenantID, arg.VpcID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const confirmSnatClaim = `-- name: ConfirmSnatClaim :exec
UPDATE network_eip_claims SET state='bound' WHERE tenant_id=$1 AND snat_id=$2 AND released_at IS NULL
`

type ConfirmSnatClaimParams struct {
	TenantID string
	SnatID   *string
}

func (q *Queries) ConfirmSnatClaim(ctx context.Context, arg ConfirmSnatClaimParams) error {
	_, err := q.db.Exec(ctx, confirmSnatClaim, arg.TenantID, arg.SnatID)
	return err
}

const getBaseConnectivity = `-- name: GetBaseConnectivity :one
SELECT tenant_id, vpc_id, cluster_id, namespace, pool_id, pool_revision, purpose, eip_id, snat_id, operation_id, state, reason, provider_ready, provider_observed_at, observed_at, terminating, version, created_at FROM network_vpc_base_connectivity WHERE tenant_id=$1 AND vpc_id=$2
`

type GetBaseConnectivityParams struct {
	TenantID string
	VpcID    string
}

func (q *Queries) GetBaseConnectivity(ctx context.Context, arg GetBaseConnectivityParams) (NetworkVpcBaseConnectivity, error) {
	row := q.db.QueryRow(ctx, getBaseConnectivity, arg.TenantID, arg.VpcID)
	var i NetworkVpcBaseConnectivity
	err := row.Scan(
		&i.TenantID,
		&i.VpcID,
		&i.ClusterID,
		&i.Namespace,
		&i.PoolID,
		&i.PoolRevision,
		&i.Purpose,
		&i.EipID,
		&i.SnatID,
		&i.OperationID,
		&i.State,
		&i.Reason,
		&i.ProviderReady,
		&i.ProviderObservedAt,
		&i.ObservedAt,
		&i.Terminating,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const getBaseForEIP = `-- name: GetBaseForEIP :one
SELECT tenant_id, vpc_id, cluster_id, namespace, pool_id, pool_revision, purpose, eip_id, snat_id, operation_id, state, reason, provider_ready, provider_observed_at, observed_at, terminating, version, created_at FROM network_vpc_base_connectivity WHERE tenant_id=$1 AND eip_id=$2
`

type GetBaseForEIPParams struct {
	TenantID string
	EipID    string
}

func (q *Queries) GetBaseForEIP(ctx context.Context, arg GetBaseForEIPParams) (NetworkVpcBaseConnectivity, error) {
	row := q.db.QueryRow(ctx, getBaseForEIP, arg.TenantID, arg.EipID)
	var i NetworkVpcBaseConnectivity
	err := row.Scan(
		&i.TenantID,
		&i.VpcID,
		&i.ClusterID,
		&i.Namespace,
		&i.PoolID,
		&i.PoolRevision,
		&i.Purpose,
		&i.EipID,
		&i.SnatID,
		&i.OperationID,
		&i.State,
		&i.Reason,
		&i.ProviderReady,
		&i.ProviderObservedAt,
		&i.ObservedAt,
		&i.Terminating,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const getBaseForSnat = `-- name: GetBaseForSnat :one
SELECT tenant_id, vpc_id, cluster_id, namespace, pool_id, pool_revision, purpose, eip_id, snat_id, operation_id, state, reason, provider_ready, provider_observed_at, observed_at, terminating, version, created_at FROM network_vpc_base_connectivity WHERE tenant_id=$1 AND snat_id=$2
`

type GetBaseForSnatParams struct {
	TenantID string
	SnatID   string
}

func (q *Queries) GetBaseForSnat(ctx context.Context, arg GetBaseForSnatParams) (NetworkVpcBaseConnectivity, error) {
	row := q.db.QueryRow(ctx, getBaseForSnat, arg.TenantID, arg.SnatID)
	var i NetworkVpcBaseConnectivity
	err := row.Scan(
		&i.TenantID,
		&i.VpcID,
		&i.ClusterID,
		&i.Namespace,
		&i.PoolID,
		&i.PoolRevision,
		&i.Purpose,
		&i.EipID,
		&i.SnatID,
		&i.OperationID,
		&i.State,
		&i.Reason,
		&i.ProviderReady,
		&i.ProviderObservedAt,
		&i.ObservedAt,
		&i.Terminating,
		&i.Version,
		&i.CreatedAt,
	)
	return i, err
}

const getConnectivityRollout = `-- name: GetConnectivityRollout :one
SELECT cluster_id, new_vpcs_enabled, legacy_aggregation_enabled, updated_at FROM network_connectivity_rollout WHERE cluster_id=$1
`

type GetConnectivityRolloutParams struct {
	ClusterID string
}

func (q *Queries) GetConnectivityRollout(ctx context.Context, arg GetConnectivityRolloutParams) (NetworkConnectivityRollout, error) {
	row := q.db.QueryRow(ctx, getConnectivityRollout, arg.ClusterID)
	var i NetworkConnectivityRollout
	err := row.Scan(
		&i.ClusterID,
		&i.NewVpcsEnabled,
		&i.LegacyAggregationEnabled,
		&i.UpdatedAt,
	)
	return i, err
}

const insertBaseConnectivity = `-- name: InsertBaseConnectivity :exec
INSERT INTO network_vpc_base_connectivity(tenant_id,vpc_id,cluster_id,namespace,pool_id,pool_revision,eip_id,snat_id,operation_id)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)
`

type InsertBaseConnectivityParams struct {
	TenantID     string
	VpcID        string
	ClusterID    string
	Namespace    string
	PoolID       string
	PoolRevision int64
	EipID        string
	SnatID       string
	OperationID  string
}

func (q *Queries) InsertBaseConnectivity(ctx context.Context, arg InsertBaseConnectivityParams) error {
	_, err := q.db.Exec(ctx, insertBaseConnectivity,
		arg.TenantID,
		arg.VpcID,
		arg.ClusterID,
		arg.Namespace,
		arg.PoolID,
		arg.PoolRevision,
		arg.EipID,
		arg.SnatID,
		arg.OperationID,
	)
	return err
}

const insertBaseEIP = `-- name: InsertBaseEIP :one
INSERT INTO network_eips(tenant_id,eip_id,cluster_id,namespace,name,description,pool_id,pool_revision,scope,managed_by,system_owner_vpc,state,created_at,updated_at,last_operation_id)
VALUES($1,$2,$3,$4,'VPC base connectivity','',$5,$6,'intranet','system',$7,'provisioning',$8,$8,$9) RETURNING tenant_id, eip_id, cluster_id, namespace, name, description, pool_id, pool_revision, address, state, reason, version, created_at, updated_at, observed_at, last_operation_id, scope, managed_by, system_owner_vpc
`

type InsertBaseEIPParams struct {
	TenantID     string
	EipID        string
	ClusterID    string
	Namespace    string
	PoolID       string
	PoolRevision int64
	VpcID        *string
	CreatedAt    time.Time
	OperationID  string
}

func (q *Queries) InsertBaseEIP(ctx context.Context, arg InsertBaseEIPParams) (NetworkEip, error) {
	row := q.db.QueryRow(ctx, insertBaseEIP,
		arg.TenantID,
		arg.EipID,
		arg.ClusterID,
		arg.Namespace,
		arg.PoolID,
		arg.PoolRevision,
		arg.VpcID,
		arg.CreatedAt,
		arg.OperationID,
	)
	var i NetworkEip
	err := row.Scan(
		&i.TenantID,
		&i.EipID,
		&i.ClusterID,
		&i.Namespace,
		&i.Name,
		&i.Description,
		&i.PoolID,
		&i.PoolRevision,
		&i.Address,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.Scope,
		&i.ManagedBy,
		&i.SystemOwnerVpc,
	)
	return i, err
}

const insertBaseSnat = `-- name: InsertBaseSnat :one
INSERT INTO network_snat_bindings(tenant_id,snat_id,cluster_id,namespace,name,description,vpc_id,eip_id,purpose,desired_enabled,state,created_at,updated_at,last_operation_id)
VALUES($1,$2,$3,$4,'VPC base connectivity','',$5,$6,'intranet',true,'provisioning',$7,$7,$8) RETURNING tenant_id, snat_id, cluster_id, namespace, name, description, vpc_id, eip_id, desired_enabled, applied_enabled, target_generation, state, reason, version, created_at, updated_at, observed_at, last_operation_id, purpose, system_owner_vpc
`

type InsertBaseSnatParams struct {
	TenantID    string
	SnatID      string
	ClusterID   string
	Namespace   string
	VpcID       string
	EipID       string
	CreatedAt   time.Time
	OperationID string
}

func (q *Queries) InsertBaseSnat(ctx context.Context, arg InsertBaseSnatParams) (NetworkSnatBinding, error) {
	row := q.db.QueryRow(ctx, insertBaseSnat,
		arg.TenantID,
		arg.SnatID,
		arg.ClusterID,
		arg.Namespace,
		arg.VpcID,
		arg.EipID,
		arg.CreatedAt,
		arg.OperationID,
	)
	var i NetworkSnatBinding
	err := row.Scan(
		&i.TenantID,
		&i.SnatID,
		&i.ClusterID,
		&i.Namespace,
		&i.Name,
		&i.Description,
		&i.VpcID,
		&i.EipID,
		&i.DesiredEnabled,
		&i.AppliedEnabled,
		&i.TargetGeneration,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.Purpose,
		&i.SystemOwnerVpc,
	)
	return i, err
}

const notifyBaseChildren = `-- name: NotifyBaseChildren :exec
UPDATE network_reconciliations r SET requested_generation=r.requested_generation+1,
 next_run_at=greatest(r.retry_not_before,least(r.next_run_at,clock_timestamp()))
FROM network_vpc_base_connectivity b WHERE NOT r.retired AND b.tenant_id=$1 AND b.vpc_id=$2 AND r.tenant_id=b.tenant_id
 AND (r.eip_id=b.eip_id OR r.snat_id=b.snat_id)
`

type NotifyBaseChildrenParams struct {
	TenantID string
	VpcID    string
}

func (q *Queries) NotifyBaseChildren(ctx context.Context, arg NotifyBaseChildrenParams) error {
	_, err := q.db.Exec(ctx, notifyBaseChildren, arg.TenantID, arg.VpcID)
	return err
}

const notifyBaseParent = `-- name: NotifyBaseParent :exec
UPDATE network_reconciliations r SET requested_generation=r.requested_generation+1,
 next_run_at=greatest(r.retry_not_before,least(r.next_run_at,clock_timestamp()))
FROM network_vpc_base_connectivity b WHERE NOT r.retired AND b.tenant_id=$1 AND r.tenant_id=b.tenant_id AND r.vpc_id=b.vpc_id
 AND (b.eip_id=$2 OR b.snat_id=$2)
`

type NotifyBaseParentParams struct {
	TenantID   string
	ResourceID string
}

func (q *Queries) NotifyBaseParent(ctx context.Context, arg NotifyBaseParentParams) error {
	_, err := q.db.Exec(ctx, notifyBaseParent, arg.TenantID, arg.ResourceID)
	return err
}

const releaseSnatClaim = `-- name: ReleaseSnatClaim :exec
UPDATE network_eip_claims SET released_at=clock_timestamp() WHERE tenant_id=$1 AND snat_id=$2 AND released_at IS NULL
`

type ReleaseSnatClaimParams struct {
	TenantID string
	SnatID   *string
}

func (q *Queries) ReleaseSnatClaim(ctx context.Context, arg ReleaseSnatClaimParams) error {
	_, err := q.db.Exec(ctx, releaseSnatClaim, arg.TenantID, arg.SnatID)
	return err
}

const requireVPCBase = `-- name: RequireVPCBase :exec
UPDATE network_vpcs SET base_connectivity_required=true WHERE tenant_id=$1 AND vpc_id=$2
`

type RequireVPCBaseParams struct {
	TenantID string
	VpcID    string
}

func (q *Queries) RequireVPCBase(ctx context.Context, arg RequireVPCBaseParams) error {
	_, err := q.db.Exec(ctx, requireVPCBase, arg.TenantID, arg.VpcID)
	return err
}

const retireActiveOperation = `-- name: RetireActiveOperation :exec
UPDATE network_operations SET state='failed',reason='CREATE_TERMINATED',completed_at=clock_timestamp(),updated_at=clock_timestamp(),next_attempt_at=NULL
WHERE tenant_id=$1 AND operation_id=$2 AND completed_at IS NULL AND kind NOT LIKE 'delete_%'
`

type RetireActiveOperationParams struct {
	TenantID    string
	OperationID string
}

func (q *Queries) RetireActiveOperation(ctx context.Context, arg RetireActiveOperationParams) error {
	_, err := q.db.Exec(ctx, retireActiveOperation, arg.TenantID, arg.OperationID)
	return err
}

const retireCancelledResource = `-- name: RetireCancelledResource :execrows
UPDATE network_reconciliations SET retired=true,next_run_at='infinity',lease_owner=NULL,lease_until=NULL,
 processed_generation=requested_generation
WHERE tenant_id=$1 AND coalesce(eip_id,snat_id)=$2
 AND lease_owner=$3::uuid AND lease_epoch=$4 AND lease_until>clock_timestamp()
`

type RetireCancelledResourceParams struct {
	TenantID   string
	ResourceID *string
	Owner      string
	Epoch      int64
}

func (q *Queries) RetireCancelledResource(ctx context.Context, arg RetireCancelledResourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, retireCancelledResource,
		arg.TenantID,
		arg.ResourceID,
		arg.Owner,
		arg.Epoch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setBaseObservation = `-- name: SetBaseObservation :exec
UPDATE network_vpc_base_connectivity SET state=$1,reason=$2,
 provider_ready=$3,provider_observed_at=$4,observed_at=$5,version=version+1
WHERE tenant_id=$6 AND vpc_id=$7
`

type SetBaseObservationParams struct {
	State              string
	Reason             string
	ProviderReady      bool
	ProviderObservedAt *time.Time
	ObservedAt         *time.Time
	TenantID           string
	VpcID              string
}

func (q *Queries) SetBaseObservation(ctx context.Context, arg SetBaseObservationParams) error {
	_, err := q.db.Exec(ctx, setBaseObservation,
		arg.State,
		arg.Reason,
		arg.ProviderReady,
		arg.ProviderObservedAt,
		arg.ObservedAt,
		arg.TenantID,
		arg.VpcID,
	)
	return err
}

const terminateBase = `-- name: TerminateBase :exec
UPDATE network_vpc_base_connectivity SET terminating=true,state='deleting',reason='',version=version+1 WHERE tenant_id=$1 AND vpc_id=$2
`

type TerminateBaseParams struct {
	TenantID string
	VpcID    string
}

func (q *Queries) TerminateBase(ctx context.Context, arg TerminateBaseParams) error {
	_, err := q.db.Exec(ctx, terminateBase, arg.TenantID, arg.VpcID)
	return err
}
