// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"
)

type NetworkIdempotency struct {
	TenantID           string
	OperationKind      string
	IdempotencyKey     string
	Fingerprint        string
	FingerprintVersion int32
	VpcID              string
	OperationID        string
	Response           []byte
	CreatedAt          time.Time
}

type NetworkOperation struct {
	TenantID       string
	OperationID    string
	VpcID          string
	Kind           string
	State          string
	Reason         string
	Attempt        int32
	ExecutionEpoch int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CompletedAt    *time.Time
	NextAttemptAt  *time.Time
}

type NetworkProviderBinding struct {
	TenantID      string
	VpcID         string
	BindingID     string
	ClusterID     string
	Namespace     string
	ProviderName  string
	ProviderUid   string
	PendingAction string
	PendingSince  *time.Time
}

type NetworkReconciliation struct {
	TenantID   string
	VpcID      string
	NextRunAt  time.Time
	LeaseOwner *string
	LeaseUntil *time.Time
	LeaseEpoch int64
}

type NetworkResourceHistory struct {
	TenantID         string
	HistoryID        string
	VpcID            string
	OperationID      *string
	Event            string
	ResourceState    string
	OperationState   string
	Reason           string
	ActorRef         string
	CallerRef        string
	CorrelationID    string
	IdentityVerified bool
	CreatedAt        time.Time
}

type NetworkVpc struct {
	TenantID        string
	VpcID           string
	Name            string
	Description     string
	Cidr            string
	State           string
	Reason          string
	Version         int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ObservedAt      *time.Time
	LastOperationID string
}
