// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observation.sql

package sqlcgen

import (
	"context"
)

const notifyAttachment = `-- name: NotifyAttachment :execrows
UPDATE network_attachments
SET requested_generation=requested_generation+1,
    next_check_at=greatest(retry_not_before,least(next_check_at,clock_timestamp()))
WHERE tenant_id=$1 AND attachment_id=$2
`

type NotifyAttachmentParams struct {
	TenantID     string
	AttachmentID string
}

func (q *Queries) NotifyAttachment(ctx context.Context, arg NotifyAttachmentParams) (int64, error) {
	result, err := q.db.Exec(ctx, notifyAttachment, arg.TenantID, arg.AttachmentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const notifyResource = `-- name: NotifyResource :execrows
UPDATE network_reconciliations
SET requested_generation=requested_generation+1,
    next_run_at=greatest(retry_not_before,least(next_run_at,clock_timestamp()))
WHERE tenant_id=$1 AND coalesce(vpc_id,subnet_id)=$2::text
`

type NotifyResourceParams struct {
	TenantID   string
	ResourceID string
}

// Observer hints may only wake already registered, tenant-scoped identities.
// Hints never revoke a live lease or mutate a public version. A failure's
// persisted backoff remains a lower bound even under an event storm.
func (q *Queries) NotifyResource(ctx context.Context, arg NotifyResourceParams) (int64, error) {
	result, err := q.db.Exec(ctx, notifyResource, arg.TenantID, arg.ResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const observationAttachments = `-- name: ObservationAttachments :many
SELECT tenant_id,attachment_id,subnet_id,vpc_id,namespace,pod_name,pod_uid,
 provider_relations,requested_generation FROM network_attachments WHERE cluster_id=$1
`

type ObservationAttachmentsParams struct {
	ClusterID string
}

type ObservationAttachmentsRow struct {
	TenantID            string
	AttachmentID        string
	SubnetID            string
	VpcID               string
	Namespace           string
	PodName             string
	PodUid              string
	ProviderRelations   []byte
	RequestedGeneration int64
}

func (q *Queries) ObservationAttachments(ctx context.Context, arg ObservationAttachmentsParams) ([]ObservationAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, observationAttachments, arg.ClusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationAttachmentsRow{}
	for rows.Next() {
		var i ObservationAttachmentsRow
		if err := rows.Scan(
			&i.TenantID,
			&i.AttachmentID,
			&i.SubnetID,
			&i.VpcID,
			&i.Namespace,
			&i.PodName,
			&i.PodUid,
			&i.ProviderRelations,
			&i.RequestedGeneration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const observationResources = `-- name: ObservationResources :many
SELECT r.tenant_id,coalesce(r.vpc_id,r.subnet_id)::text AS resource_id,
 r.requested_generation,b.resource_kind,b.namespace,b.provider_name,b.provider_uid
FROM network_reconciliations r JOIN network_provider_bindings b
 ON b.tenant_id=r.tenant_id AND coalesce(b.vpc_id,b.subnet_id)=coalesce(r.vpc_id,r.subnet_id)
WHERE b.cluster_id=$1
`

type ObservationResourcesParams struct {
	ClusterID string
}

type ObservationResourcesRow struct {
	TenantID            string
	ResourceID          string
	RequestedGeneration int64
	ResourceKind        string
	Namespace           string
	ProviderName        string
	ProviderUid         string
}

// Complete range inventory for observer recovery only; not a product query.
func (q *Queries) ObservationResources(ctx context.Context, arg ObservationResourcesParams) ([]ObservationResourcesRow, error) {
	rows, err := q.db.Query(ctx, observationResources, arg.ClusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationResourcesRow{}
	for rows.Next() {
		var i ObservationResourcesRow
		if err := rows.Scan(
			&i.TenantID,
			&i.ResourceID,
			&i.RequestedGeneration,
			&i.ResourceKind,
			&i.Namespace,
			&i.ProviderName,
			&i.ProviderUid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
