// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vpcs.sql

package sqlcgen

import (
	"context"
	"time"
)

const databaseTime = `-- name: DatabaseTime :one
SELECT clock_timestamp()::timestamptz AS now
`

func (q *Queries) DatabaseTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, databaseTime)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}

const getIdempotency = `-- name: GetIdempotency :one
SELECT tenant_id, operation_kind, idempotency_key, fingerprint, fingerprint_version, vpc_id, operation_id, response, created_at, subnet_id FROM network_idempotency
WHERE tenant_id = $1 AND operation_kind = 'create_vpc' AND idempotency_key = $2
`

type GetIdempotencyParams struct {
	TenantID       string
	IdempotencyKey string
}

func (q *Queries) GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (NetworkIdempotency, error) {
	row := q.db.QueryRow(ctx, getIdempotency, arg.TenantID, arg.IdempotencyKey)
	var i NetworkIdempotency
	err := row.Scan(
		&i.TenantID,
		&i.OperationKind,
		&i.IdempotencyKey,
		&i.Fingerprint,
		&i.FingerprintVersion,
		&i.VpcID,
		&i.OperationID,
		&i.Response,
		&i.CreatedAt,
		&i.SubnetID,
	)
	return i, err
}

const getOperation = `-- name: GetOperation :one
SELECT tenant_id, operation_id, vpc_id, kind, state, reason, attempt, execution_epoch, created_at, updated_at, completed_at, next_attempt_at, subnet_id FROM network_operations WHERE tenant_id = $1 AND operation_id = $2
`

type GetOperationParams struct {
	TenantID    string
	OperationID string
}

func (q *Queries) GetOperation(ctx context.Context, arg GetOperationParams) (NetworkOperation, error) {
	row := q.db.QueryRow(ctx, getOperation, arg.TenantID, arg.OperationID)
	var i NetworkOperation
	err := row.Scan(
		&i.TenantID,
		&i.OperationID,
		&i.VpcID,
		&i.Kind,
		&i.State,
		&i.Reason,
		&i.Attempt,
		&i.ExecutionEpoch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.NextAttemptAt,
		&i.SubnetID,
	)
	return i, err
}

const getVPC = `-- name: GetVPC :one
SELECT v.tenant_id, v.vpc_id, v.name, v.description, v.cidr, v.state, v.reason, v.version, v.created_at, v.updated_at, v.observed_at, v.last_operation_id, (SELECT count(*) FROM network_subnets s WHERE s.tenant_id=v.tenant_id AND s.vpc_id=v.vpc_id AND s.state<>'deleted')::bigint AS subnet_count FROM network_vpcs v WHERE v.tenant_id=$1 AND v.vpc_id=$2
`

type GetVPCParams struct {
	TenantID string
	VpcID    string
}

type GetVPCRow struct {
	NetworkVpc  NetworkVpc
	SubnetCount int64
}

func (q *Queries) GetVPC(ctx context.Context, arg GetVPCParams) (GetVPCRow, error) {
	row := q.db.QueryRow(ctx, getVPC, arg.TenantID, arg.VpcID)
	var i GetVPCRow
	err := row.Scan(
		&i.NetworkVpc.TenantID,
		&i.NetworkVpc.VpcID,
		&i.NetworkVpc.Name,
		&i.NetworkVpc.Description,
		&i.NetworkVpc.Cidr,
		&i.NetworkVpc.State,
		&i.NetworkVpc.Reason,
		&i.NetworkVpc.Version,
		&i.NetworkVpc.CreatedAt,
		&i.NetworkVpc.UpdatedAt,
		&i.NetworkVpc.ObservedAt,
		&i.NetworkVpc.LastOperationID,
		&i.SubnetCount,
	)
	return i, err
}

const insertBinding = `-- name: InsertBinding :exec
INSERT INTO network_provider_bindings (tenant_id,vpc_id,subnet_id,binding_id,cluster_id,namespace,provider_name,resource_kind)
VALUES ($1,NULLIF($2::text,''),NULLIF($3::text,''),$4,$5,$6,$7,CASE WHEN $3::text='' THEN 'vpc' ELSE 'subnet' END)
`

type InsertBindingParams struct {
	TenantID     string
	VpcID        string
	SubnetID     string
	BindingID    string
	ClusterID    string
	Namespace    string
	ProviderName string
}

func (q *Queries) InsertBinding(ctx context.Context, arg InsertBindingParams) error {
	_, err := q.db.Exec(ctx, insertBinding,
		arg.TenantID,
		arg.VpcID,
		arg.SubnetID,
		arg.BindingID,
		arg.ClusterID,
		arg.Namespace,
		arg.ProviderName,
	)
	return err
}

const insertHistory = `-- name: InsertHistory :exec
INSERT INTO network_resource_history
(tenant_id,history_id,vpc_id,subnet_id,operation_id,event,resource_state,operation_state,reason,actor_ref,caller_ref,correlation_id,created_at)
VALUES ($1,$2,NULLIF($3::text,''),NULLIF($4::text,''),$5,$6,$7,$8,$9,$10,$11,$12,$13)
`

type InsertHistoryParams struct {
	TenantID       string
	HistoryID      string
	VpcID          string
	SubnetID       string
	OperationID    *string
	Event          string
	ResourceState  string
	OperationState string
	Reason         string
	ActorRef       string
	CallerRef      string
	CorrelationID  string
	CreatedAt      time.Time
}

func (q *Queries) InsertHistory(ctx context.Context, arg InsertHistoryParams) error {
	_, err := q.db.Exec(ctx, insertHistory,
		arg.TenantID,
		arg.HistoryID,
		arg.VpcID,
		arg.SubnetID,
		arg.OperationID,
		arg.Event,
		arg.ResourceState,
		arg.OperationState,
		arg.Reason,
		arg.ActorRef,
		arg.CallerRef,
		arg.CorrelationID,
		arg.CreatedAt,
	)
	return err
}

const insertIdempotency = `-- name: InsertIdempotency :exec
INSERT INTO network_idempotency
(tenant_id,operation_kind,idempotency_key,fingerprint,fingerprint_version,vpc_id,operation_id,response,created_at)
VALUES ($1,'create_vpc',$2,$3,1,$4::text,$5,$6,$7)
`

type InsertIdempotencyParams struct {
	TenantID       string
	IdempotencyKey string
	Fingerprint    string
	VpcID          string
	OperationID    string
	Response       []byte
	CreatedAt      time.Time
}

func (q *Queries) InsertIdempotency(ctx context.Context, arg InsertIdempotencyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotency,
		arg.TenantID,
		arg.IdempotencyKey,
		arg.Fingerprint,
		arg.VpcID,
		arg.OperationID,
		arg.Response,
		arg.CreatedAt,
	)
	return err
}

const insertOperation = `-- name: InsertOperation :exec
INSERT INTO network_operations (tenant_id,operation_id,vpc_id,subnet_id,kind,state,created_at,updated_at,next_attempt_at)
VALUES ($1,$2,NULLIF($3::text,''),NULLIF($4::text,''),$5,'queued',$6,$6,$6)
`

type InsertOperationParams struct {
	TenantID    string
	OperationID string
	VpcID       string
	SubnetID    string
	Kind        string
	CreatedAt   time.Time
}

func (q *Queries) InsertOperation(ctx context.Context, arg InsertOperationParams) error {
	_, err := q.db.Exec(ctx, insertOperation,
		arg.TenantID,
		arg.OperationID,
		arg.VpcID,
		arg.SubnetID,
		arg.Kind,
		arg.CreatedAt,
	)
	return err
}

const insertReconciliation = `-- name: InsertReconciliation :exec
INSERT INTO network_reconciliations (tenant_id,vpc_id,subnet_id,next_run_at) VALUES ($1,NULLIF($2::text,''),NULLIF($3::text,''),$4)
`

type InsertReconciliationParams struct {
	TenantID  string
	VpcID     string
	SubnetID  string
	NextRunAt time.Time
}

func (q *Queries) InsertReconciliation(ctx context.Context, arg InsertReconciliationParams) error {
	_, err := q.db.Exec(ctx, insertReconciliation,
		arg.TenantID,
		arg.VpcID,
		arg.SubnetID,
		arg.NextRunAt,
	)
	return err
}

const insertVPC = `-- name: InsertVPC :one
INSERT INTO network_vpcs (tenant_id,vpc_id,name,description,cidr,state,created_at,updated_at,last_operation_id)
VALUES ($1,$2,$3,$4,$5,'provisioning',$6,$6,$7)
RETURNING tenant_id, vpc_id, name, description, cidr, state, reason, version, created_at, updated_at, observed_at, last_operation_id
`

type InsertVPCParams struct {
	TenantID        string
	VpcID           string
	Name            string
	Description     string
	Cidr            string
	CreatedAt       time.Time
	LastOperationID string
}

func (q *Queries) InsertVPC(ctx context.Context, arg InsertVPCParams) (NetworkVpc, error) {
	row := q.db.QueryRow(ctx, insertVPC,
		arg.TenantID,
		arg.VpcID,
		arg.Name,
		arg.Description,
		arg.Cidr,
		arg.CreatedAt,
		arg.LastOperationID,
	)
	var i NetworkVpc
	err := row.Scan(
		&i.TenantID,
		&i.VpcID,
		&i.Name,
		&i.Description,
		&i.Cidr,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
	)
	return i, err
}

const listVPCs = `-- name: ListVPCs :many
SELECT v.tenant_id, v.vpc_id, v.name, v.description, v.cidr, v.state, v.reason, v.version, v.created_at, v.updated_at, v.observed_at, v.last_operation_id, (SELECT count(*) FROM network_subnets s WHERE s.tenant_id=v.tenant_id AND s.vpc_id=v.vpc_id AND s.state<>'deleted')::bigint AS subnet_count FROM network_vpcs v
WHERE v.tenant_id = $1
  AND ($2::text = '' OR v.name = $2)
  AND (($3::text = '' AND v.state <> 'deleted') OR v.state = $3)
  AND ($4::text = '' OR (v.created_at, v.vpc_id) < ($5::timestamptz, $4::text))
ORDER BY v.created_at DESC, v.vpc_id DESC
LIMIT $6::integer
`

type ListVPCsParams struct {
	TenantID       string
	NameFilter     string
	StateFilter    string
	AfterID        string
	AfterCreatedAt time.Time
	MaxResults     int32
}

type ListVPCsRow struct {
	NetworkVpc  NetworkVpc
	SubnetCount int64
}

func (q *Queries) ListVPCs(ctx context.Context, arg ListVPCsParams) ([]ListVPCsRow, error) {
	rows, err := q.db.Query(ctx, listVPCs,
		arg.TenantID,
		arg.NameFilter,
		arg.StateFilter,
		arg.AfterID,
		arg.AfterCreatedAt,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVPCsRow{}
	for rows.Next() {
		var i ListVPCsRow
		if err := rows.Scan(
			&i.NetworkVpc.TenantID,
			&i.NetworkVpc.VpcID,
			&i.NetworkVpc.Name,
			&i.NetworkVpc.Description,
			&i.NetworkVpc.Cidr,
			&i.NetworkVpc.State,
			&i.NetworkVpc.Reason,
			&i.NetworkVpc.Version,
			&i.NetworkVpc.CreatedAt,
			&i.NetworkVpc.UpdatedAt,
			&i.NetworkVpc.ObservedAt,
			&i.NetworkVpc.LastOperationID,
			&i.SubnetCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCreationKey = `-- name: LockCreationKey :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text || ':create_vpc:' || $2::text, 0))
`

type LockCreationKeyParams struct {
	TenantID       string
	IdempotencyKey string
}

func (q *Queries) LockCreationKey(ctx context.Context, arg LockCreationKeyParams) error {
	_, err := q.db.Exec(ctx, lockCreationKey, arg.TenantID, arg.IdempotencyKey)
	return err
}
