// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vpcs.sql

package sqlcgen

import (
	"context"
	"time"
)

const databaseTime = `-- name: DatabaseTime :one
SELECT clock_timestamp()::timestamptz AS now
`

func (q *Queries) DatabaseTime(ctx context.Context) (time.Time, error) {
	row := q.db.QueryRow(ctx, databaseTime)
	var now time.Time
	err := row.Scan(&now)
	return now, err
}

const getIdempotency = `-- name: GetIdempotency :one
SELECT tenant_id, operation_kind, idempotency_key, fingerprint, fingerprint_version, vpc_id, operation_id, response, created_at FROM network_idempotency
WHERE tenant_id = $1 AND operation_kind = 'create_vpc' AND idempotency_key = $2
`

type GetIdempotencyParams struct {
	TenantID       string
	IdempotencyKey string
}

func (q *Queries) GetIdempotency(ctx context.Context, arg GetIdempotencyParams) (NetworkIdempotency, error) {
	row := q.db.QueryRow(ctx, getIdempotency, arg.TenantID, arg.IdempotencyKey)
	var i NetworkIdempotency
	err := row.Scan(
		&i.TenantID,
		&i.OperationKind,
		&i.IdempotencyKey,
		&i.Fingerprint,
		&i.FingerprintVersion,
		&i.VpcID,
		&i.OperationID,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const getOperation = `-- name: GetOperation :one
SELECT tenant_id, operation_id, vpc_id, kind, state, reason, attempt, execution_epoch, created_at, updated_at, completed_at, next_attempt_at FROM network_operations WHERE tenant_id = $1 AND operation_id = $2
`

type GetOperationParams struct {
	TenantID    string
	OperationID string
}

func (q *Queries) GetOperation(ctx context.Context, arg GetOperationParams) (NetworkOperation, error) {
	row := q.db.QueryRow(ctx, getOperation, arg.TenantID, arg.OperationID)
	var i NetworkOperation
	err := row.Scan(
		&i.TenantID,
		&i.OperationID,
		&i.VpcID,
		&i.Kind,
		&i.State,
		&i.Reason,
		&i.Attempt,
		&i.ExecutionEpoch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.NextAttemptAt,
	)
	return i, err
}

const getVPC = `-- name: GetVPC :one
SELECT tenant_id, vpc_id, name, description, cidr, state, reason, version, created_at, updated_at, observed_at, last_operation_id FROM network_vpcs WHERE tenant_id = $1 AND vpc_id = $2
`

type GetVPCParams struct {
	TenantID string
	VpcID    string
}

func (q *Queries) GetVPC(ctx context.Context, arg GetVPCParams) (NetworkVpc, error) {
	row := q.db.QueryRow(ctx, getVPC, arg.TenantID, arg.VpcID)
	var i NetworkVpc
	err := row.Scan(
		&i.TenantID,
		&i.VpcID,
		&i.Name,
		&i.Description,
		&i.Cidr,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
	)
	return i, err
}

const insertBinding = `-- name: InsertBinding :exec
INSERT INTO network_provider_bindings (tenant_id,vpc_id,binding_id,cluster_id,namespace,provider_name)
VALUES ($1,$2,$3,$4,$5,$6)
`

type InsertBindingParams struct {
	TenantID     string
	VpcID        string
	BindingID    string
	ClusterID    string
	Namespace    string
	ProviderName string
}

func (q *Queries) InsertBinding(ctx context.Context, arg InsertBindingParams) error {
	_, err := q.db.Exec(ctx, insertBinding,
		arg.TenantID,
		arg.VpcID,
		arg.BindingID,
		arg.ClusterID,
		arg.Namespace,
		arg.ProviderName,
	)
	return err
}

const insertHistory = `-- name: InsertHistory :exec
INSERT INTO network_resource_history
(tenant_id,history_id,vpc_id,operation_id,event,resource_state,operation_state,reason,actor_ref,caller_ref,correlation_id,created_at)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)
`

type InsertHistoryParams struct {
	TenantID       string
	HistoryID      string
	VpcID          string
	OperationID    *string
	Event          string
	ResourceState  string
	OperationState string
	Reason         string
	ActorRef       string
	CallerRef      string
	CorrelationID  string
	CreatedAt      time.Time
}

func (q *Queries) InsertHistory(ctx context.Context, arg InsertHistoryParams) error {
	_, err := q.db.Exec(ctx, insertHistory,
		arg.TenantID,
		arg.HistoryID,
		arg.VpcID,
		arg.OperationID,
		arg.Event,
		arg.ResourceState,
		arg.OperationState,
		arg.Reason,
		arg.ActorRef,
		arg.CallerRef,
		arg.CorrelationID,
		arg.CreatedAt,
	)
	return err
}

const insertIdempotency = `-- name: InsertIdempotency :exec
INSERT INTO network_idempotency
(tenant_id,operation_kind,idempotency_key,fingerprint,fingerprint_version,vpc_id,operation_id,response,created_at)
VALUES ($1,'create_vpc',$2,$3,1,$4,$5,$6,$7)
`

type InsertIdempotencyParams struct {
	TenantID       string
	IdempotencyKey string
	Fingerprint    string
	VpcID          string
	OperationID    string
	Response       []byte
	CreatedAt      time.Time
}

func (q *Queries) InsertIdempotency(ctx context.Context, arg InsertIdempotencyParams) error {
	_, err := q.db.Exec(ctx, insertIdempotency,
		arg.TenantID,
		arg.IdempotencyKey,
		arg.Fingerprint,
		arg.VpcID,
		arg.OperationID,
		arg.Response,
		arg.CreatedAt,
	)
	return err
}

const insertOperation = `-- name: InsertOperation :exec
INSERT INTO network_operations (tenant_id,operation_id,vpc_id,kind,state,created_at,updated_at,next_attempt_at)
VALUES ($1,$2,$3,$4,'queued',$5,$5,$5)
`

type InsertOperationParams struct {
	TenantID    string
	OperationID string
	VpcID       string
	Kind        string
	CreatedAt   time.Time
}

func (q *Queries) InsertOperation(ctx context.Context, arg InsertOperationParams) error {
	_, err := q.db.Exec(ctx, insertOperation,
		arg.TenantID,
		arg.OperationID,
		arg.VpcID,
		arg.Kind,
		arg.CreatedAt,
	)
	return err
}

const insertReconciliation = `-- name: InsertReconciliation :exec
INSERT INTO network_reconciliations (tenant_id,vpc_id,next_run_at) VALUES ($1,$2,$3)
`

type InsertReconciliationParams struct {
	TenantID  string
	VpcID     string
	NextRunAt time.Time
}

func (q *Queries) InsertReconciliation(ctx context.Context, arg InsertReconciliationParams) error {
	_, err := q.db.Exec(ctx, insertReconciliation, arg.TenantID, arg.VpcID, arg.NextRunAt)
	return err
}

const insertVPC = `-- name: InsertVPC :one
INSERT INTO network_vpcs (tenant_id,vpc_id,name,description,cidr,state,created_at,updated_at,last_operation_id)
VALUES ($1,$2,$3,$4,$5,'provisioning',$6,$6,$7)
RETURNING tenant_id, vpc_id, name, description, cidr, state, reason, version, created_at, updated_at, observed_at, last_operation_id
`

type InsertVPCParams struct {
	TenantID        string
	VpcID           string
	Name            string
	Description     string
	Cidr            string
	CreatedAt       time.Time
	LastOperationID string
}

func (q *Queries) InsertVPC(ctx context.Context, arg InsertVPCParams) (NetworkVpc, error) {
	row := q.db.QueryRow(ctx, insertVPC,
		arg.TenantID,
		arg.VpcID,
		arg.Name,
		arg.Description,
		arg.Cidr,
		arg.CreatedAt,
		arg.LastOperationID,
	)
	var i NetworkVpc
	err := row.Scan(
		&i.TenantID,
		&i.VpcID,
		&i.Name,
		&i.Description,
		&i.Cidr,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
	)
	return i, err
}

const listVPCs = `-- name: ListVPCs :many
SELECT tenant_id, vpc_id, name, description, cidr, state, reason, version, created_at, updated_at, observed_at, last_operation_id FROM network_vpcs
WHERE tenant_id = $1
  AND ($2::text = '' OR name = $2)
  AND (($3::text = '' AND state <> 'deleted') OR state = $3)
  AND ($4::text = '' OR (created_at, vpc_id) < ($5::timestamptz, $4::text))
ORDER BY created_at DESC, vpc_id DESC
LIMIT $6::integer
`

type ListVPCsParams struct {
	TenantID       string
	NameFilter     string
	StateFilter    string
	AfterID        string
	AfterCreatedAt time.Time
	MaxResults     int32
}

func (q *Queries) ListVPCs(ctx context.Context, arg ListVPCsParams) ([]NetworkVpc, error) {
	rows, err := q.db.Query(ctx, listVPCs,
		arg.TenantID,
		arg.NameFilter,
		arg.StateFilter,
		arg.AfterID,
		arg.AfterCreatedAt,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NetworkVpc{}
	for rows.Next() {
		var i NetworkVpc
		if err := rows.Scan(
			&i.TenantID,
			&i.VpcID,
			&i.Name,
			&i.Description,
			&i.Cidr,
			&i.State,
			&i.Reason,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ObservedAt,
			&i.LastOperationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCreationKey = `-- name: LockCreationKey :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text || ':create_vpc:' || $2::text, 0))
`

type LockCreationKeyParams struct {
	TenantID       string
	IdempotencyKey string
}

func (q *Queries) LockCreationKey(ctx context.Context, arg LockCreationKeyParams) error {
	_, err := q.db.Exec(ctx, lockCreationKey, arg.TenantID, arg.IdempotencyKey)
	return err
}
