// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: worker.sql

package sqlcgen

import (
	"context"
	"time"
)

const acquireLease = `-- name: AcquireLease :one
UPDATE network_reconciliations
SET lease_owner=$1::uuid, lease_epoch=lease_epoch+1,
    lease_until=clock_timestamp()+$2::bigint*interval '1 microsecond'
WHERE tenant_id=$3 AND coalesce(vpc_id,subnet_id,eip_id,snat_id,lb_id)=$4::text
  AND (lease_until IS NULL OR lease_until <= clock_timestamp())
RETURNING tenant_id, vpc_id, next_run_at, lease_owner, lease_until, lease_epoch, subnet_id, reconciliation_id, requested_generation, processed_generation, retry_not_before, evidence_hash, evidence_applied_at, eip_id, snat_id, retired, lb_id
`

type AcquireLeaseParams struct {
	Owner       string
	LeaseMicros int64
	TenantID    string
	ResourceID  string
}

func (q *Queries) AcquireLease(ctx context.Context, arg AcquireLeaseParams) (NetworkReconciliation, error) {
	row := q.db.QueryRow(ctx, acquireLease,
		arg.Owner,
		arg.LeaseMicros,
		arg.TenantID,
		arg.ResourceID,
	)
	var i NetworkReconciliation
	err := row.Scan(
		&i.TenantID,
		&i.VpcID,
		&i.NextRunAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LeaseEpoch,
		&i.SubnetID,
		&i.ReconciliationID,
		&i.RequestedGeneration,
		&i.ProcessedGeneration,
		&i.RetryNotBefore,
		&i.EvidenceHash,
		&i.EvidenceAppliedAt,
		&i.EipID,
		&i.SnatID,
		&i.Retired,
		&i.LbID,
	)
	return i, err
}

const admitDeletion = `-- name: AdmitDeletion :one
UPDATE network_vpcs SET state='deleting', reason='', last_operation_id=$1,
    version=version+1, updated_at=clock_timestamp()
WHERE tenant_id=$2 AND vpc_id=$3 AND version=$4
RETURNING tenant_id, vpc_id, name, description, cidr, state, reason, version, created_at, updated_at, observed_at, last_operation_id, base_connectivity_required
`

type AdmitDeletionParams struct {
	OperationID string
	TenantID    string
	VpcID       string
	Version     int64
}

func (q *Queries) AdmitDeletion(ctx context.Context, arg AdmitDeletionParams) (NetworkVpc, error) {
	row := q.db.QueryRow(ctx, admitDeletion,
		arg.OperationID,
		arg.TenantID,
		arg.VpcID,
		arg.Version,
	)
	var i NetworkVpc
	err := row.Scan(
		&i.TenantID,
		&i.VpcID,
		&i.Name,
		&i.Description,
		&i.Cidr,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.BaseConnectivityRequired,
	)
	return i, err
}

const advanceVPC = `-- name: AdvanceVPC :one
UPDATE network_vpcs
SET state=$1, reason=$2, version=version+1, updated_at=clock_timestamp(),
    observed_at=CASE WHEN $3::boolean THEN $4::timestamptz ELSE observed_at END
WHERE tenant_id=$5 AND vpc_id=$6 AND version=$7
RETURNING tenant_id, vpc_id, name, description, cidr, state, reason, version, created_at, updated_at, observed_at, last_operation_id, base_connectivity_required
`

type AdvanceVPCParams struct {
	State      string
	Reason     string
	Observed   bool
	ObservedAt *time.Time
	TenantID   string
	VpcID      string
	Version    int64
}

func (q *Queries) AdvanceVPC(ctx context.Context, arg AdvanceVPCParams) (NetworkVpc, error) {
	row := q.db.QueryRow(ctx, advanceVPC,
		arg.State,
		arg.Reason,
		arg.Observed,
		arg.ObservedAt,
		arg.TenantID,
		arg.VpcID,
		arg.Version,
	)
	var i NetworkVpc
	err := row.Scan(
		&i.TenantID,
		&i.VpcID,
		&i.Name,
		&i.Description,
		&i.Cidr,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.BaseConnectivityRequired,
	)
	return i, err
}

const beginProviderMutation = `-- name: BeginProviderMutation :execrows
UPDATE network_provider_bindings
SET pending_action=$1, pending_since=clock_timestamp(),
    create_dispatched=create_dispatched OR $1::text='create',
    provider_uid=CASE WHEN provider_uid='' THEN $2::text ELSE provider_uid END
WHERE tenant_id=$3 AND coalesce(vpc_id,subnet_id,eip_id,snat_id,lb_id)=$4::text AND binding_id=$5
  AND (provider_uid='' OR provider_uid=$2)
  AND (($1::text='create' AND pending_action='')
       OR ($1='update' AND provider_uid<>'' AND pending_action IN ('','update'))
       OR ($1='delete' AND (pending_action IN ('','delete') OR $2::text<>'')))
`

type BeginProviderMutationParams struct {
	Action     string
	Identity   string
	TenantID   string
	ResourceID string
	BindingID  string
}

func (q *Queries) BeginProviderMutation(ctx context.Context, arg BeginProviderMutationParams) (int64, error) {
	result, err := q.db.Exec(ctx, beginProviderMutation,
		arg.Action,
		arg.Identity,
		arg.TenantID,
		arg.ResourceID,
		arg.BindingID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const checkLease = `-- name: CheckLease :one
SELECT tenant_id, vpc_id, next_run_at, lease_owner, lease_until, lease_epoch, subnet_id, reconciliation_id, requested_generation, processed_generation, retry_not_before, evidence_hash, evidence_applied_at, eip_id, snat_id, retired, lb_id FROM network_reconciliations
WHERE tenant_id=$1 AND coalesce(vpc_id,subnet_id,eip_id,snat_id,lb_id)=$2::text AND lease_owner=$3 AND lease_epoch=$4
  AND lease_until > clock_timestamp()
FOR UPDATE
`

type CheckLeaseParams struct {
	TenantID   string
	ResourceID string
	LeaseOwner *string
	LeaseEpoch int64
}

func (q *Queries) CheckLease(ctx context.Context, arg CheckLeaseParams) (NetworkReconciliation, error) {
	row := q.db.QueryRow(ctx, checkLease,
		arg.TenantID,
		arg.ResourceID,
		arg.LeaseOwner,
		arg.LeaseEpoch,
	)
	var i NetworkReconciliation
	err := row.Scan(
		&i.TenantID,
		&i.VpcID,
		&i.NextRunAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LeaseEpoch,
		&i.SubnetID,
		&i.ReconciliationID,
		&i.RequestedGeneration,
		&i.ProcessedGeneration,
		&i.RetryNotBefore,
		&i.EvidenceHash,
		&i.EvidenceAppliedAt,
		&i.EipID,
		&i.SnatID,
		&i.Retired,
		&i.LbID,
	)
	return i, err
}

const completeAttempt = `-- name: CompleteAttempt :execrows
UPDATE network_operations
SET state=$1, reason=$2, updated_at=clock_timestamp(),
    completed_at=CASE WHEN $1::text IN ('succeeded','failed') THEN clock_timestamp() ELSE NULL END,
    next_attempt_at=CASE WHEN $1::text IN ('succeeded','failed') THEN NULL
      ELSE clock_timestamp()+$3::bigint*interval '1 microsecond' END
WHERE tenant_id=$4 AND coalesce(vpc_id,subnet_id,eip_id,snat_id,lb_id)=$5::text
  AND operation_id=$6 AND execution_epoch=$7
  AND state NOT IN ('succeeded','failed')
`

type CompleteAttemptParams struct {
	State       string
	Reason      string
	DelayMicros int64
	TenantID    string
	ResourceID  string
	OperationID string
	Epoch       int64
}

func (q *Queries) CompleteAttempt(ctx context.Context, arg CompleteAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeAttempt,
		arg.State,
		arg.Reason,
		arg.DelayMicros,
		arg.TenantID,
		arg.ResourceID,
		arg.OperationID,
		arg.Epoch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getBinding = `-- name: GetBinding :one
SELECT tenant_id, vpc_id, binding_id, cluster_id, namespace, provider_name, provider_uid, pending_action, pending_since, subnet_id, resource_kind, eip_id, snat_id, create_dispatched, lb_id FROM network_provider_bindings WHERE tenant_id=$1 AND coalesce(vpc_id,subnet_id,eip_id,snat_id,lb_id)=$2::text
`

type GetBindingParams struct {
	TenantID   string
	ResourceID string
}

func (q *Queries) GetBinding(ctx context.Context, arg GetBindingParams) (NetworkProviderBinding, error) {
	row := q.db.QueryRow(ctx, getBinding, arg.TenantID, arg.ResourceID)
	var i NetworkProviderBinding
	err := row.Scan(
		&i.TenantID,
		&i.VpcID,
		&i.BindingID,
		&i.ClusterID,
		&i.Namespace,
		&i.ProviderName,
		&i.ProviderUid,
		&i.PendingAction,
		&i.PendingSince,
		&i.SubnetID,
		&i.ResourceKind,
		&i.EipID,
		&i.SnatID,
		&i.CreateDispatched,
		&i.LbID,
	)
	return i, err
}

const lockDueResourceParent = `-- name: LockDueResourceParent :one
SELECT v.tenant_id, v.vpc_id, r.subnet_id
FROM network_reconciliations r
LEFT JOIN network_subnets s ON s.tenant_id=r.tenant_id AND s.subnet_id=r.subnet_id
JOIN network_vpcs v ON v.tenant_id=r.tenant_id AND v.vpc_id=coalesce(r.vpc_id,s.vpc_id)
WHERE r.next_run_at <= clock_timestamp()
  AND (r.lease_until IS NULL OR r.lease_until <= clock_timestamp())
ORDER BY r.next_run_at, coalesce(r.vpc_id,r.subnet_id,r.eip_id,r.snat_id,r.lb_id)
LIMIT 1 FOR UPDATE OF v SKIP LOCKED
`

type LockDueResourceParentRow struct {
	TenantID string
	VpcID    string
	SubnetID *string
}

// Schedule both resource kinds by due time. Always lock the parent VPC first,
// including for Subnet work, preserving the common parent -> child lock order.
// This worker-only query crosses tenants; subsequent operations use its scope.
func (q *Queries) LockDueResourceParent(ctx context.Context) (LockDueResourceParentRow, error) {
	row := q.db.QueryRow(ctx, lockDueResourceParent)
	var i LockDueResourceParentRow
	err := row.Scan(&i.TenantID, &i.VpcID, &i.SubnetID)
	return i, err
}

const lockVPC = `-- name: LockVPC :one
SELECT tenant_id, vpc_id, name, description, cidr, state, reason, version, created_at, updated_at, observed_at, last_operation_id, base_connectivity_required FROM network_vpcs WHERE tenant_id=$1 AND vpc_id=$2 FOR UPDATE
`

type LockVPCParams struct {
	TenantID string
	VpcID    string
}

func (q *Queries) LockVPC(ctx context.Context, arg LockVPCParams) (NetworkVpc, error) {
	row := q.db.QueryRow(ctx, lockVPC, arg.TenantID, arg.VpcID)
	var i NetworkVpc
	err := row.Scan(
		&i.TenantID,
		&i.VpcID,
		&i.Name,
		&i.Description,
		&i.Cidr,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.BaseConnectivityRequired,
	)
	return i, err
}

const releaseLease = `-- name: ReleaseLease :execrows
UPDATE network_reconciliations
SET lease_owner=NULL, lease_until=NULL,
    processed_generation=greatest(processed_generation,$1::bigint),
    evidence_hash=CASE WHEN $2::boolean THEN $3::text ELSE evidence_hash END,
    evidence_applied_at=CASE WHEN $2::boolean THEN clock_timestamp() ELSE evidence_applied_at END,
    retry_not_before=CASE WHEN $4::boolean THEN clock_timestamp()+$5::bigint*interval '1 microsecond' ELSE '1970-01-01 UTC'::timestamptz END,
    next_run_at=CASE WHEN requested_generation>$1::bigint AND NOT $4::boolean THEN clock_timestamp() ELSE clock_timestamp()+$5::bigint*interval '1 microsecond' END
WHERE tenant_id=$6 AND coalesce(vpc_id,subnet_id,eip_id,snat_id,lb_id)=$7::text
  AND lease_owner=$8 AND lease_epoch=$9 AND lease_until>clock_timestamp()
`

type ReleaseLeaseParams struct {
	CoveredGeneration int64
	Observed          bool
	EvidenceHash      string
	Backoff           bool
	DelayMicros       int64
	TenantID          string
	ResourceID        string
	Owner             *string
	Epoch             int64
}

func (q *Queries) ReleaseLease(ctx context.Context, arg ReleaseLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, releaseLease,
		arg.CoveredGeneration,
		arg.Observed,
		arg.EvidenceHash,
		arg.Backoff,
		arg.DelayMicros,
		arg.TenantID,
		arg.ResourceID,
		arg.Owner,
		arg.Epoch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const runOperation = `-- name: RunOperation :one
UPDATE network_operations SET state='running', attempt=attempt+1,
    execution_epoch=$1, updated_at=clock_timestamp()
WHERE tenant_id=$2 AND coalesce(vpc_id,subnet_id,eip_id,snat_id,lb_id)=$3::text
  AND operation_id=$4 AND state NOT IN ('succeeded','failed')
RETURNING tenant_id, operation_id, vpc_id, kind, state, reason, attempt, execution_epoch, created_at, updated_at, completed_at, next_attempt_at, subnet_id, eip_id, snat_id, lb_id
`

type RunOperationParams struct {
	Epoch       int64
	TenantID    string
	ResourceID  string
	OperationID string
}

func (q *Queries) RunOperation(ctx context.Context, arg RunOperationParams) (NetworkOperation, error) {
	row := q.db.QueryRow(ctx, runOperation,
		arg.Epoch,
		arg.TenantID,
		arg.ResourceID,
		arg.OperationID,
	)
	var i NetworkOperation
	err := row.Scan(
		&i.TenantID,
		&i.OperationID,
		&i.VpcID,
		&i.Kind,
		&i.State,
		&i.Reason,
		&i.Attempt,
		&i.ExecutionEpoch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.NextAttemptAt,
		&i.SubnetID,
		&i.EipID,
		&i.SnatID,
		&i.LbID,
	)
	return i, err
}

const saveBindingObservation = `-- name: SaveBindingObservation :execrows
UPDATE network_provider_bindings
SET provider_uid=CASE WHEN provider_uid='' THEN $1::text ELSE provider_uid END,
    pending_action=CASE WHEN $2::boolean THEN '' ELSE pending_action END,
    pending_since=CASE WHEN $2::boolean THEN NULL ELSE pending_since END
WHERE tenant_id=$3 AND coalesce(vpc_id,subnet_id,eip_id,snat_id,lb_id)=$4::text AND binding_id=$5
  AND (provider_uid='' OR provider_uid=$1)
`

type SaveBindingObservationParams struct {
	Identity     string
	ClearPending bool
	TenantID     string
	ResourceID   string
	BindingID    string
}

func (q *Queries) SaveBindingObservation(ctx context.Context, arg SaveBindingObservationParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveBindingObservation,
		arg.Identity,
		arg.ClearPending,
		arg.TenantID,
		arg.ResourceID,
		arg.BindingID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const scheduleDeletion = `-- name: ScheduleDeletion :execrows
UPDATE network_reconciliations SET next_run_at=clock_timestamp(),
    lease_owner=NULL, lease_until=NULL, lease_epoch=lease_epoch+1
WHERE tenant_id=$1 AND coalesce(vpc_id,subnet_id,eip_id,snat_id,lb_id)=$2::text
`

type ScheduleDeletionParams struct {
	TenantID   string
	ResourceID string
}

func (q *Queries) ScheduleDeletion(ctx context.Context, arg ScheduleDeletionParams) (int64, error) {
	result, err := q.db.Exec(ctx, scheduleDeletion, arg.TenantID, arg.ResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
