package data

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"strings"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"github.com/zhangzhe-ctrl/ani-network-service/internal/biz"
	"github.com/zhangzhe-ctrl/ani-network-service/internal/data/sqlcgen"
	"github.com/zhangzhe-ctrl/ani-network-service/migrations"
)

type Placement struct {
	ClusterID       string
	NamespacePrefix string
}

type Postgres struct {
	pool      *pgxpool.Pool
	queries   *sqlcgen.Queries
	placement Placement
}

func OpenPostgres(ctx context.Context, dsn string, placement Placement) (*Postgres, error) {
	if strings.TrimSpace(placement.ClusterID) == "" || len(placement.ClusterID) > 128 ||
		!regexp.MustCompile(`^[a-z][a-z0-9-]{0,25}-$`).MatchString(placement.NamespacePrefix) {
		return nil, fmt.Errorf("cluster ID and a DNS namespace prefix ending in '-' are required")
	}
	config, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		return nil, fmt.Errorf("invalid runtime database configuration")
	}
	config.MaxConns = 8
	pool, err := pgxpool.NewWithConfig(ctx, config)
	if err != nil {
		return nil, databaseFailure(err)
	}
	repository := &Postgres{pool: pool, queries: sqlcgen.New(pool), placement: placement}
	if err := repository.CheckReady(ctx); err != nil {
		pool.Close()
		return nil, err
	}
	return repository, nil
}

func (p *Postgres) Close() { p.pool.Close() }

// CheckReady inspects infrastructure catalogs; product SQL is generated by sqlc.
func (p *Postgres) CheckReady(ctx context.Context) error {
	var unsafe bool
	if err := p.pool.QueryRow(ctx, `SELECT rolsuper OR rolbypassrls OR rolcreatedb OR rolcreaterole OR
		has_schema_privilege(current_user,'public','CREATE') OR
 has_database_privilege(current_user,current_database(),'CREATE') OR has_database_privilege(current_user,current_database(),'TEMP') OR EXISTS (
 SELECT 1 FROM pg_roles privileged WHERE (privileged.rolsuper OR privileged.rolbypassrls OR privileged.rolcreatedb OR privileged.rolcreaterole)
 AND pg_has_role(current_user,privileged.oid,'SET')) FROM pg_roles WHERE rolname=current_user`).Scan(&unsafe); err != nil {
		return databaseFailure(err)
	}
	if unsafe {
		return fmt.Errorf("runtime database role has administrative privileges")
	}
	var count, unsafeTables int
	err := p.pool.QueryRow(ctx, `SELECT count(*), count(*) FILTER (
		WHERE c.relrowsecurity OR c.relforcerowsecurity OR pg_has_role(current_user,c.relowner,'SET'))
		FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace
		WHERE n.nspname='public' AND c.relkind='r' AND c.relname=ANY($1::text[])`, networkTables).Scan(&count, &unsafeTables)
	if err != nil {
		return databaseFailure(err)
	}
	if count != len(networkTables) || unsafeTables != 0 {
		return fmt.Errorf("Network schema missing, RLS enabled, or runtime role owns a table")
	}
	var versionCount int
	var checksum string
	err = p.pool.QueryRow(ctx, "SELECT count(*), coalesce(max(checksum),'') FROM network_schema_version WHERE version=1").Scan(&versionCount, &checksum)
	if err != nil {
		return databaseFailure(err)
	}
	body, err := migrations.Files.ReadFile("0001_vpc.sql")
	if err != nil {
		return err
	}
	digest := sha256.Sum256(body)
	if versionCount != 1 || checksum != hex.EncodeToString(digest[:]) {
		return fmt.Errorf("Network schema version/checksum does not match this executable")
	}
	var versions int
	if err := p.pool.QueryRow(ctx, "SELECT count(*) FROM network_schema_version").Scan(&versions); err != nil {
		return databaseFailure(err)
	}
	if versions != 1 {
		return fmt.Errorf("unsupported Network schema version")
	}
	return nil
}

func (p *Postgres) AcceptVPC(ctx context.Context, intent biz.VPCIntent, attribution biz.Attribution) (biz.VPC, error) {
	tx, err := p.pool.Begin(ctx)
	if err != nil {
		return biz.VPC{}, databaseFailure(err)
	}
	defer tx.Rollback(ctx)
	q := p.queries.WithTx(tx)
	if err := q.LockCreationKey(ctx, sqlcgen.LockCreationKeyParams{TenantID: intent.TenantID, IdempotencyKey: intent.IdempotencyKey}); err != nil {
		return biz.VPC{}, databaseFailure(err)
	}
	previous, err := q.GetIdempotency(ctx, sqlcgen.GetIdempotencyParams{TenantID: intent.TenantID, IdempotencyKey: intent.IdempotencyKey})
	if err == nil {
		if previous.FingerprintVersion != 1 || previous.Fingerprint != intent.Fingerprint() {
			return biz.VPC{}, biz.Fail(biz.IdempotencyConflict, "key already accepted a different VPC intent")
		}
		var value biz.VPC
		if err := json.Unmarshal(previous.Response, &value); err != nil {
			return biz.VPC{}, databaseFailure(err)
		}
		if value.ID != previous.VpcID || value.TenantID != intent.TenantID || value.LastOperationID != previous.OperationID {
			return biz.VPC{}, databaseFailure(fmt.Errorf("invalid acceptance snapshot"))
		}
		return value, nil
	}
	if !errors.Is(err, pgx.ErrNoRows) {
		return biz.VPC{}, databaseFailure(err)
	}
	now, err := q.DatabaseTime(ctx)
	if err != nil {
		return biz.VPC{}, databaseFailure(err)
	}
	vpcID := "vpc_" + strings.ReplaceAll(uuid.NewString(), "-", "")
	operationID := uuid.NewString()
	row, err := q.InsertVPC(ctx, sqlcgen.InsertVPCParams{
		TenantID: intent.TenantID, VpcID: vpcID, Name: intent.Name,
		Description: intent.Description, Cidr: intent.CIDR, CreatedAt: now, LastOperationID: operationID,
	})
	if err != nil {
		return biz.VPC{}, databaseFailure(err)
	}
	if err := q.InsertOperation(ctx, sqlcgen.InsertOperationParams{
		TenantID: intent.TenantID, OperationID: operationID, VpcID: vpcID, Kind: "create_vpc", CreatedAt: now,
	}); err != nil {
		return biz.VPC{}, databaseFailure(err)
	}
	if err := q.InsertReconciliation(ctx, sqlcgen.InsertReconciliationParams{TenantID: intent.TenantID, VpcID: vpcID, NextRunAt: now}); err != nil {
		return biz.VPC{}, databaseFailure(err)
	}
	if err := q.InsertBinding(ctx, sqlcgen.InsertBindingParams{
		TenantID: intent.TenantID, VpcID: vpcID, BindingID: uuid.NewString(), ClusterID: p.placement.ClusterID,
		Namespace: p.placement.NamespacePrefix + intent.TenantID, ProviderName: strings.Replace(vpcID, "_", "-", 1),
	}); err != nil {
		return biz.VPC{}, databaseFailure(err)
	}
	value := vpc(row)
	value.ObservationStale = true
	snapshot, err := json.Marshal(value)
	if err != nil {
		return biz.VPC{}, databaseFailure(err)
	}
	if err := q.InsertIdempotency(ctx, sqlcgen.InsertIdempotencyParams{
		TenantID: intent.TenantID, IdempotencyKey: intent.IdempotencyKey, Fingerprint: intent.Fingerprint(),
		VpcID: vpcID, OperationID: operationID, Response: snapshot, CreatedAt: now,
	}); err != nil {
		return biz.VPC{}, databaseFailure(err)
	}
	if err := q.InsertHistory(ctx, sqlcgen.InsertHistoryParams{
		TenantID: intent.TenantID, HistoryID: uuid.NewString(), VpcID: vpcID, OperationID: &operationID,
		Event: "create_accepted", ResourceState: string(biz.Provisioning), OperationState: string(biz.Queued),
		ActorRef: attribution.Actor, CallerRef: attribution.DirectCaller, CorrelationID: attribution.CorrelationID, CreatedAt: now,
	}); err != nil {
		return biz.VPC{}, databaseFailure(err)
	}
	if err := tx.Commit(ctx); err != nil {
		return biz.VPC{}, databaseFailure(err)
	}
	return value, nil
}

func (p *Postgres) GetVPC(ctx context.Context, tenant, id string) (biz.VPC, error) {
	row, err := p.queries.GetVPC(ctx, sqlcgen.GetVPCParams{TenantID: tenant, VpcID: id})
	return vpc(row), databaseFailure(err)
}

func (p *Postgres) GetOperation(ctx context.Context, tenant, id string) (biz.Operation, error) {
	row, err := p.queries.GetOperation(ctx, sqlcgen.GetOperationParams{TenantID: tenant, OperationID: id})
	return operation(row), databaseFailure(err)
}

func (p *Postgres) ListVPCs(ctx context.Context, tenant string, filter biz.VPCFilter) ([]biz.VPC, error) {
	rows, err := p.queries.ListVPCs(ctx, sqlcgen.ListVPCsParams{
		TenantID: tenant, NameFilter: filter.Name, StateFilter: filter.State,
		AfterID: filter.AfterID, AfterCreatedAt: filter.AfterCreatedAt, MaxResults: filter.Limit,
	})
	if err != nil {
		return nil, databaseFailure(err)
	}
	result := make([]biz.VPC, 0, len(rows))
	for _, row := range rows {
		result = append(result, vpc(row))
	}
	return result, nil
}

func vpc(row sqlcgen.NetworkVpc) biz.VPC {
	return biz.VPC{
		ID: row.VpcID, TenantID: row.TenantID, Name: row.Name, Description: row.Description, CIDR: row.Cidr,
		State: biz.ResourceState(row.State), Reason: biz.Reason(row.Reason), Version: row.Version,
		CreatedAt: row.CreatedAt, UpdatedAt: row.UpdatedAt, ObservedAt: row.ObservedAt, LastOperationID: row.LastOperationID,
	}
}

func operation(row sqlcgen.NetworkOperation) biz.Operation {
	return biz.Operation{
		ID: row.OperationID, TenantID: row.TenantID, ResourceID: row.VpcID, Kind: row.Kind,
		State: biz.OperationState(row.State), Reason: biz.Reason(row.Reason), CreatedAt: row.CreatedAt,
		UpdatedAt: row.UpdatedAt, CompletedAt: row.CompletedAt, NextAttemptAt: row.NextAttemptAt,
	}
}

func databaseFailure(err error) error {
	if err == nil {
		return nil
	}
	if errors.Is(err, pgx.ErrNoRows) {
		return biz.Fail(biz.ResourceNotFound, "resource not found")
	}
	if errors.Is(err, context.Canceled) || errors.Is(err, context.DeadlineExceeded) {
		return err
	}
	return &biz.Error{Reason: biz.DependencyUnavailable, Message: "Network database unavailable", Cause: err}
}
