apiVersion: networking.kubercloud.com/v1
kind: VlanNetwork
metadata:
  name: pubdebug-20260917-vlan0
  labels:
    manual.ani.io/run: pubdebug-20260917
spec:
  devName: ens35
  vlanID: 0
---
apiVersion: networking.kubercloud.com/v1
kind: EIPGateway
metadata:
  name: pubdebug-20260917-egress
  labels:
    manual.ani.io/run: pubdebug-20260917
spec:
  scope: Public
  egressType: Host
---
apiVersion: networking.kubercloud.com/v1
kind: Subnet
metadata:
  name: pubdebug-20260917-intranet
  labels:
    manual.ani.io/run: pubdebug-20260917
  namespace: kcn-system
spec:
  type: Intranet
  ipVersion: IPv4
  cidrBlock: 10.242.252.0/24
  gatewayIP: 10.242.252.1
  allowedNamespaces:
    from: Selector
    selector:
      matchLabels:
        manual.ani.io/run: pubdebug-20260917
---
apiVersion: networking.kubercloud.com/v1
kind: Subnet
metadata:
  name: pubdebug-20260917-public
  labels:
    manual.ani.io/run: pubdebug-20260917
  namespace: kcn-system
spec:
  type: Public
  ipVersion: IPv4
  cidrBlock: 172.16.102.0/24
  gatewayIP: 172.16.102.2
  gateway: pubdebug-20260917-egress
  underlayConfig:
    vlanNetwork: pubdebug-20260917-vlan0
    gatewayIP: 172.16.102.1
  excludeIPs:
  - 172.16.102.1..172.16.102.191
  - 172.16.102.208..172.16.102.254
  enableDHCP: false
  natOutgoing: false
  allowedNamespaces:
    from: Selector
    selector:
      matchLabels:
        manual.ani.io/run: pubdebug-20260917
