apiVersion: networking.kubercloud.com/v1
kind: EIP
metadata:
  name: public-eip
  labels:
    manual.ani.io/run: pubdebug-20260917
  namespace: pubdebug-20260917
spec:
  subnet: kcn-system/pubdebug-20260917-public
  ipVersion: IPv4
  ipAddress: 172.16.102.194
---
apiVersion: networking.kubercloud.com/v1
kind: EIP
metadata:
  name: dual-eip
  labels:
    manual.ani.io/run: pubdebug-20260917
  namespace: pubdebug-20260917
spec:
  subnet: kcn-system/pubdebug-20260917-public
  ipVersion: IPv4
  ipAddress: 172.16.102.195
---
apiVersion: networking.kubercloud.com/v1
kind: EIP
metadata:
  name: snat-eip
  labels:
    manual.ani.io/run: pubdebug-20260917
  namespace: pubdebug-20260917
spec:
  subnet: kcn-system/pubdebug-20260917-public
  ipVersion: IPv4
  ipAddress: 172.16.102.196
