// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: network/v1/egress.proto

package networkv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TenantEgressService_CreateEIP_FullMethodName            = "/network.v1.TenantEgressService/CreateEIP"
	TenantEgressService_GetEIP_FullMethodName               = "/network.v1.TenantEgressService/GetEIP"
	TenantEgressService_ListEIPs_FullMethodName             = "/network.v1.TenantEgressService/ListEIPs"
	TenantEgressService_DeleteEIP_FullMethodName            = "/network.v1.TenantEgressService/DeleteEIP"
	TenantEgressService_BindVPCSnat_FullMethodName          = "/network.v1.TenantEgressService/BindVPCSnat"
	TenantEgressService_GetVPCSnat_FullMethodName           = "/network.v1.TenantEgressService/GetVPCSnat"
	TenantEgressService_GetVPCSnatBinding_FullMethodName    = "/network.v1.TenantEgressService/GetVPCSnatBinding"
	TenantEgressService_SetVPCSnatEnabled_FullMethodName    = "/network.v1.TenantEgressService/SetVPCSnatEnabled"
	TenantEgressService_DeleteVPCSnatBinding_FullMethodName = "/network.v1.TenantEgressService/DeleteVPCSnatBinding"
)

// TenantEgressServiceClient is the client API for TenantEgressService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Authorization is supplied by the trusted inbound context, never by a role or
// permission in a request. A different target_tenant_id requires delegation.
// Every method is restricted to tenant-managed Public resources. System-managed
// Intranet resources are excluded from lists and lookups (including guessed IDs).
type TenantEgressServiceClient interface {
	CreateEIP(ctx context.Context, in *CreateEIPRequest, opts ...grpc.CallOption) (*CreateEIPResponse, error)
	GetEIP(ctx context.Context, in *GetEIPRequest, opts ...grpc.CallOption) (*GetEIPResponse, error)
	ListEIPs(ctx context.Context, in *ListEIPsRequest, opts ...grpc.CallOption) (*ListEIPsResponse, error)
	DeleteEIP(ctx context.Context, in *DeleteEIPRequest, opts ...grpc.CallOption) (*DeleteEIPResponse, error)
	BindVPCSnat(ctx context.Context, in *BindVPCSnatRequest, opts ...grpc.CallOption) (*BindVPCSnatResponse, error)
	GetVPCSnat(ctx context.Context, in *GetVPCSnatRequest, opts ...grpc.CallOption) (*GetVPCSnatResponse, error)
	GetVPCSnatBinding(ctx context.Context, in *GetVPCSnatBindingRequest, opts ...grpc.CallOption) (*GetVPCSnatBindingResponse, error)
	SetVPCSnatEnabled(ctx context.Context, in *SetVPCSnatEnabledRequest, opts ...grpc.CallOption) (*SetVPCSnatEnabledResponse, error)
	DeleteVPCSnatBinding(ctx context.Context, in *DeleteVPCSnatBindingRequest, opts ...grpc.CallOption) (*DeleteVPCSnatBindingResponse, error)
}

type tenantEgressServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantEgressServiceClient(cc grpc.ClientConnInterface) TenantEgressServiceClient {
	return &tenantEgressServiceClient{cc}
}

func (c *tenantEgressServiceClient) CreateEIP(ctx context.Context, in *CreateEIPRequest, opts ...grpc.CallOption) (*CreateEIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEIPResponse)
	err := c.cc.Invoke(ctx, TenantEgressService_CreateEIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantEgressServiceClient) GetEIP(ctx context.Context, in *GetEIPRequest, opts ...grpc.CallOption) (*GetEIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEIPResponse)
	err := c.cc.Invoke(ctx, TenantEgressService_GetEIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantEgressServiceClient) ListEIPs(ctx context.Context, in *ListEIPsRequest, opts ...grpc.CallOption) (*ListEIPsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEIPsResponse)
	err := c.cc.Invoke(ctx, TenantEgressService_ListEIPs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantEgressServiceClient) DeleteEIP(ctx context.Context, in *DeleteEIPRequest, opts ...grpc.CallOption) (*DeleteEIPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEIPResponse)
	err := c.cc.Invoke(ctx, TenantEgressService_DeleteEIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantEgressServiceClient) BindVPCSnat(ctx context.Context, in *BindVPCSnatRequest, opts ...grpc.CallOption) (*BindVPCSnatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindVPCSnatResponse)
	err := c.cc.Invoke(ctx, TenantEgressService_BindVPCSnat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantEgressServiceClient) GetVPCSnat(ctx context.Context, in *GetVPCSnatRequest, opts ...grpc.CallOption) (*GetVPCSnatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVPCSnatResponse)
	err := c.cc.Invoke(ctx, TenantEgressService_GetVPCSnat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantEgressServiceClient) GetVPCSnatBinding(ctx context.Context, in *GetVPCSnatBindingRequest, opts ...grpc.CallOption) (*GetVPCSnatBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVPCSnatBindingResponse)
	err := c.cc.Invoke(ctx, TenantEgressService_GetVPCSnatBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantEgressServiceClient) SetVPCSnatEnabled(ctx context.Context, in *SetVPCSnatEnabledRequest, opts ...grpc.CallOption) (*SetVPCSnatEnabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetVPCSnatEnabledResponse)
	err := c.cc.Invoke(ctx, TenantEgressService_SetVPCSnatEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantEgressServiceClient) DeleteVPCSnatBinding(ctx context.Context, in *DeleteVPCSnatBindingRequest, opts ...grpc.CallOption) (*DeleteVPCSnatBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVPCSnatBindingResponse)
	err := c.cc.Invoke(ctx, TenantEgressService_DeleteVPCSnatBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantEgressServiceServer is the server API for TenantEgressService service.
// All implementations must embed UnimplementedTenantEgressServiceServer
// for forward compatibility.
//
// Authorization is supplied by the trusted inbound context, never by a role or
// permission in a request. A different target_tenant_id requires delegation.
// Every method is restricted to tenant-managed Public resources. System-managed
// Intranet resources are excluded from lists and lookups (including guessed IDs).
type TenantEgressServiceServer interface {
	CreateEIP(context.Context, *CreateEIPRequest) (*CreateEIPResponse, error)
	GetEIP(context.Context, *GetEIPRequest) (*GetEIPResponse, error)
	ListEIPs(context.Context, *ListEIPsRequest) (*ListEIPsResponse, error)
	DeleteEIP(context.Context, *DeleteEIPRequest) (*DeleteEIPResponse, error)
	BindVPCSnat(context.Context, *BindVPCSnatRequest) (*BindVPCSnatResponse, error)
	GetVPCSnat(context.Context, *GetVPCSnatRequest) (*GetVPCSnatResponse, error)
	GetVPCSnatBinding(context.Context, *GetVPCSnatBindingRequest) (*GetVPCSnatBindingResponse, error)
	SetVPCSnatEnabled(context.Context, *SetVPCSnatEnabledRequest) (*SetVPCSnatEnabledResponse, error)
	DeleteVPCSnatBinding(context.Context, *DeleteVPCSnatBindingRequest) (*DeleteVPCSnatBindingResponse, error)
	mustEmbedUnimplementedTenantEgressServiceServer()
}

// UnimplementedTenantEgressServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTenantEgressServiceServer struct{}

func (UnimplementedTenantEgressServiceServer) CreateEIP(context.Context, *CreateEIPRequest) (*CreateEIPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEIP not implemented")
}
func (UnimplementedTenantEgressServiceServer) GetEIP(context.Context, *GetEIPRequest) (*GetEIPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEIP not implemented")
}
func (UnimplementedTenantEgressServiceServer) ListEIPs(context.Context, *ListEIPsRequest) (*ListEIPsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEIPs not implemented")
}
func (UnimplementedTenantEgressServiceServer) DeleteEIP(context.Context, *DeleteEIPRequest) (*DeleteEIPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEIP not implemented")
}
func (UnimplementedTenantEgressServiceServer) BindVPCSnat(context.Context, *BindVPCSnatRequest) (*BindVPCSnatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindVPCSnat not implemented")
}
func (UnimplementedTenantEgressServiceServer) GetVPCSnat(context.Context, *GetVPCSnatRequest) (*GetVPCSnatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVPCSnat not implemented")
}
func (UnimplementedTenantEgressServiceServer) GetVPCSnatBinding(context.Context, *GetVPCSnatBindingRequest) (*GetVPCSnatBindingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVPCSnatBinding not implemented")
}
func (UnimplementedTenantEgressServiceServer) SetVPCSnatEnabled(context.Context, *SetVPCSnatEnabledRequest) (*SetVPCSnatEnabledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetVPCSnatEnabled not implemented")
}
func (UnimplementedTenantEgressServiceServer) DeleteVPCSnatBinding(context.Context, *DeleteVPCSnatBindingRequest) (*DeleteVPCSnatBindingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVPCSnatBinding not implemented")
}
func (UnimplementedTenantEgressServiceServer) mustEmbedUnimplementedTenantEgressServiceServer() {}
func (UnimplementedTenantEgressServiceServer) testEmbeddedByValue()                             {}

// UnsafeTenantEgressServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantEgressServiceServer will
// result in compilation errors.
type UnsafeTenantEgressServiceServer interface {
	mustEmbedUnimplementedTenantEgressServiceServer()
}

func RegisterTenantEgressServiceServer(s grpc.ServiceRegistrar, srv TenantEgressServiceServer) {
	// If the following call pancis, it indicates UnimplementedTenantEgressServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TenantEgressService_ServiceDesc, srv)
}

func _TenantEgressService_CreateEIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantEgressServiceServer).CreateEIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantEgressService_CreateEIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantEgressServiceServer).CreateEIP(ctx, req.(*CreateEIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantEgressService_GetEIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantEgressServiceServer).GetEIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantEgressService_GetEIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantEgressServiceServer).GetEIP(ctx, req.(*GetEIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantEgressService_ListEIPs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEIPsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantEgressServiceServer).ListEIPs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantEgressService_ListEIPs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantEgressServiceServer).ListEIPs(ctx, req.(*ListEIPsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantEgressService_DeleteEIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEIPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantEgressServiceServer).DeleteEIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantEgressService_DeleteEIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantEgressServiceServer).DeleteEIP(ctx, req.(*DeleteEIPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantEgressService_BindVPCSnat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindVPCSnatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantEgressServiceServer).BindVPCSnat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantEgressService_BindVPCSnat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantEgressServiceServer).BindVPCSnat(ctx, req.(*BindVPCSnatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantEgressService_GetVPCSnat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVPCSnatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantEgressServiceServer).GetVPCSnat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantEgressService_GetVPCSnat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantEgressServiceServer).GetVPCSnat(ctx, req.(*GetVPCSnatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantEgressService_GetVPCSnatBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVPCSnatBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantEgressServiceServer).GetVPCSnatBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantEgressService_GetVPCSnatBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantEgressServiceServer).GetVPCSnatBinding(ctx, req.(*GetVPCSnatBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantEgressService_SetVPCSnatEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetVPCSnatEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantEgressServiceServer).SetVPCSnatEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantEgressService_SetVPCSnatEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantEgressServiceServer).SetVPCSnatEnabled(ctx, req.(*SetVPCSnatEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantEgressService_DeleteVPCSnatBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVPCSnatBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantEgressServiceServer).DeleteVPCSnatBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantEgressService_DeleteVPCSnatBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantEgressServiceServer).DeleteVPCSnatBinding(ctx, req.(*DeleteVPCSnatBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TenantEgressService_ServiceDesc is the grpc.ServiceDesc for TenantEgressService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TenantEgressService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "network.v1.TenantEgressService",
	HandlerType: (*TenantEgressServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateEIP",
			Handler:    _TenantEgressService_CreateEIP_Handler,
		},
		{
			MethodName: "GetEIP",
			Handler:    _TenantEgressService_GetEIP_Handler,
		},
		{
			MethodName: "ListEIPs",
			Handler:    _TenantEgressService_ListEIPs_Handler,
		},
		{
			MethodName: "DeleteEIP",
			Handler:    _TenantEgressService_DeleteEIP_Handler,
		},
		{
			MethodName: "BindVPCSnat",
			Handler:    _TenantEgressService_BindVPCSnat_Handler,
		},
		{
			MethodName: "GetVPCSnat",
			Handler:    _TenantEgressService_GetVPCSnat_Handler,
		},
		{
			MethodName: "GetVPCSnatBinding",
			Handler:    _TenantEgressService_GetVPCSnatBinding_Handler,
		},
		{
			MethodName: "SetVPCSnatEnabled",
			Handler:    _TenantEgressService_SetVPCSnatEnabled_Handler,
		},
		{
			MethodName: "DeleteVPCSnatBinding",
			Handler:    _TenantEgressService_DeleteVPCSnatBinding_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "network/v1/egress.proto",
}

const (
	PlatformNetworkService_ListNodeInterfaces_FullMethodName               = "/network.v1.PlatformNetworkService/ListNodeInterfaces"
	PlatformNetworkService_AdoptNetworkDevice_FullMethodName               = "/network.v1.PlatformNetworkService/AdoptNetworkDevice"
	PlatformNetworkService_GetNetworkDevice_FullMethodName                 = "/network.v1.PlatformNetworkService/GetNetworkDevice"
	PlatformNetworkService_CreateVlanNetwork_FullMethodName                = "/network.v1.PlatformNetworkService/CreateVlanNetwork"
	PlatformNetworkService_GetVlanNetwork_FullMethodName                   = "/network.v1.PlatformNetworkService/GetVlanNetwork"
	PlatformNetworkService_ListVlanNetworks_FullMethodName                 = "/network.v1.PlatformNetworkService/ListVlanNetworks"
	PlatformNetworkService_DeleteVlanNetwork_FullMethodName                = "/network.v1.PlatformNetworkService/DeleteVlanNetwork"
	PlatformNetworkService_CreateEgressGateway_FullMethodName              = "/network.v1.PlatformNetworkService/CreateEgressGateway"
	PlatformNetworkService_GetEgressGateway_FullMethodName                 = "/network.v1.PlatformNetworkService/GetEgressGateway"
	PlatformNetworkService_ListEgressGateways_FullMethodName               = "/network.v1.PlatformNetworkService/ListEgressGateways"
	PlatformNetworkService_DeleteEgressGateway_FullMethodName              = "/network.v1.PlatformNetworkService/DeleteEgressGateway"
	PlatformNetworkService_CreatePublicAddressPool_FullMethodName          = "/network.v1.PlatformNetworkService/CreatePublicAddressPool"
	PlatformNetworkService_GetPublicAddressPool_FullMethodName             = "/network.v1.PlatformNetworkService/GetPublicAddressPool"
	PlatformNetworkService_ListPublicAddressPools_FullMethodName           = "/network.v1.PlatformNetworkService/ListPublicAddressPools"
	PlatformNetworkService_DeletePublicAddressPool_FullMethodName          = "/network.v1.PlatformNetworkService/DeletePublicAddressPool"
	PlatformNetworkService_RecordPublicPoolVerification_FullMethodName     = "/network.v1.PlatformNetworkService/RecordPublicPoolVerification"
	PlatformNetworkService_SetPublicPoolAllocationEnabled_FullMethodName   = "/network.v1.PlatformNetworkService/SetPublicPoolAllocationEnabled"
	PlatformNetworkService_SetDefaultPublicPool_FullMethodName             = "/network.v1.PlatformNetworkService/SetDefaultPublicPool"
	PlatformNetworkService_CreateIntranetAddressPool_FullMethodName        = "/network.v1.PlatformNetworkService/CreateIntranetAddressPool"
	PlatformNetworkService_GetIntranetAddressPool_FullMethodName           = "/network.v1.PlatformNetworkService/GetIntranetAddressPool"
	PlatformNetworkService_ListIntranetAddressPools_FullMethodName         = "/network.v1.PlatformNetworkService/ListIntranetAddressPools"
	PlatformNetworkService_DeleteIntranetAddressPool_FullMethodName        = "/network.v1.PlatformNetworkService/DeleteIntranetAddressPool"
	PlatformNetworkService_RecordIntranetPoolVerification_FullMethodName   = "/network.v1.PlatformNetworkService/RecordIntranetPoolVerification"
	PlatformNetworkService_SetIntranetPoolAllocationEnabled_FullMethodName = "/network.v1.PlatformNetworkService/SetIntranetPoolAllocationEnabled"
	PlatformNetworkService_SetDefaultIntranetPool_FullMethodName           = "/network.v1.PlatformNetworkService/SetDefaultIntranetPool"
	PlatformNetworkService_GetPlatformNetworkCapabilities_FullMethodName   = "/network.v1.PlatformNetworkService/GetPlatformNetworkCapabilities"
	PlatformNetworkService_GetPlatformOperation_FullMethodName             = "/network.v1.PlatformNetworkService/GetPlatformOperation"
)

// PlatformNetworkServiceClient is the client API for PlatformNetworkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Separate platform scope, with no fictitious tenant. Management authorization
// does not automatically grant permission to act for a tenant.
type PlatformNetworkServiceClient interface {
	ListNodeInterfaces(ctx context.Context, in *ListNodeInterfacesRequest, opts ...grpc.CallOption) (*ListNodeInterfacesResponse, error)
	AdoptNetworkDevice(ctx context.Context, in *AdoptNetworkDeviceRequest, opts ...grpc.CallOption) (*AdoptNetworkDeviceResponse, error)
	GetNetworkDevice(ctx context.Context, in *GetNetworkDeviceRequest, opts ...grpc.CallOption) (*GetNetworkDeviceResponse, error)
	CreateVlanNetwork(ctx context.Context, in *CreateVlanNetworkRequest, opts ...grpc.CallOption) (*CreateVlanNetworkResponse, error)
	GetVlanNetwork(ctx context.Context, in *GetVlanNetworkRequest, opts ...grpc.CallOption) (*GetVlanNetworkResponse, error)
	ListVlanNetworks(ctx context.Context, in *ListVlanNetworksRequest, opts ...grpc.CallOption) (*ListVlanNetworksResponse, error)
	DeleteVlanNetwork(ctx context.Context, in *DeleteVlanNetworkRequest, opts ...grpc.CallOption) (*DeleteVlanNetworkResponse, error)
	CreateEgressGateway(ctx context.Context, in *CreateEgressGatewayRequest, opts ...grpc.CallOption) (*CreateEgressGatewayResponse, error)
	GetEgressGateway(ctx context.Context, in *GetEgressGatewayRequest, opts ...grpc.CallOption) (*GetEgressGatewayResponse, error)
	ListEgressGateways(ctx context.Context, in *ListEgressGatewaysRequest, opts ...grpc.CallOption) (*ListEgressGatewaysResponse, error)
	DeleteEgressGateway(ctx context.Context, in *DeleteEgressGatewayRequest, opts ...grpc.CallOption) (*DeleteEgressGatewayResponse, error)
	CreatePublicAddressPool(ctx context.Context, in *CreatePublicAddressPoolRequest, opts ...grpc.CallOption) (*CreatePublicAddressPoolResponse, error)
	GetPublicAddressPool(ctx context.Context, in *GetPublicAddressPoolRequest, opts ...grpc.CallOption) (*GetPublicAddressPoolResponse, error)
	ListPublicAddressPools(ctx context.Context, in *ListPublicAddressPoolsRequest, opts ...grpc.CallOption) (*ListPublicAddressPoolsResponse, error)
	DeletePublicAddressPool(ctx context.Context, in *DeletePublicAddressPoolRequest, opts ...grpc.CallOption) (*DeletePublicAddressPoolResponse, error)
	RecordPublicPoolVerification(ctx context.Context, in *RecordPublicPoolVerificationRequest, opts ...grpc.CallOption) (*RecordPublicPoolVerificationResponse, error)
	SetPublicPoolAllocationEnabled(ctx context.Context, in *SetPublicPoolAllocationEnabledRequest, opts ...grpc.CallOption) (*SetPublicPoolAllocationEnabledResponse, error)
	SetDefaultPublicPool(ctx context.Context, in *SetDefaultPublicPoolRequest, opts ...grpc.CallOption) (*SetDefaultPublicPoolResponse, error)
	CreateIntranetAddressPool(ctx context.Context, in *CreateIntranetAddressPoolRequest, opts ...grpc.CallOption) (*CreateIntranetAddressPoolResponse, error)
	GetIntranetAddressPool(ctx context.Context, in *GetIntranetAddressPoolRequest, opts ...grpc.CallOption) (*GetIntranetAddressPoolResponse, error)
	ListIntranetAddressPools(ctx context.Context, in *ListIntranetAddressPoolsRequest, opts ...grpc.CallOption) (*ListIntranetAddressPoolsResponse, error)
	DeleteIntranetAddressPool(ctx context.Context, in *DeleteIntranetAddressPoolRequest, opts ...grpc.CallOption) (*DeleteIntranetAddressPoolResponse, error)
	RecordIntranetPoolVerification(ctx context.Context, in *RecordIntranetPoolVerificationRequest, opts ...grpc.CallOption) (*RecordIntranetPoolVerificationResponse, error)
	SetIntranetPoolAllocationEnabled(ctx context.Context, in *SetIntranetPoolAllocationEnabledRequest, opts ...grpc.CallOption) (*SetIntranetPoolAllocationEnabledResponse, error)
	SetDefaultIntranetPool(ctx context.Context, in *SetDefaultIntranetPoolRequest, opts ...grpc.CallOption) (*SetDefaultIntranetPoolResponse, error)
	GetPlatformNetworkCapabilities(ctx context.Context, in *GetPlatformNetworkCapabilitiesRequest, opts ...grpc.CallOption) (*GetPlatformNetworkCapabilitiesResponse, error)
	GetPlatformOperation(ctx context.Context, in *GetPlatformOperationRequest, opts ...grpc.CallOption) (*GetPlatformOperationResponse, error)
}

type platformNetworkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPlatformNetworkServiceClient(cc grpc.ClientConnInterface) PlatformNetworkServiceClient {
	return &platformNetworkServiceClient{cc}
}

func (c *platformNetworkServiceClient) ListNodeInterfaces(ctx context.Context, in *ListNodeInterfacesRequest, opts ...grpc.CallOption) (*ListNodeInterfacesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListNodeInterfacesResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_ListNodeInterfaces_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) AdoptNetworkDevice(ctx context.Context, in *AdoptNetworkDeviceRequest, opts ...grpc.CallOption) (*AdoptNetworkDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AdoptNetworkDeviceResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_AdoptNetworkDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) GetNetworkDevice(ctx context.Context, in *GetNetworkDeviceRequest, opts ...grpc.CallOption) (*GetNetworkDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNetworkDeviceResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_GetNetworkDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) CreateVlanNetwork(ctx context.Context, in *CreateVlanNetworkRequest, opts ...grpc.CallOption) (*CreateVlanNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateVlanNetworkResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_CreateVlanNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) GetVlanNetwork(ctx context.Context, in *GetVlanNetworkRequest, opts ...grpc.CallOption) (*GetVlanNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetVlanNetworkResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_GetVlanNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) ListVlanNetworks(ctx context.Context, in *ListVlanNetworksRequest, opts ...grpc.CallOption) (*ListVlanNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListVlanNetworksResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_ListVlanNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) DeleteVlanNetwork(ctx context.Context, in *DeleteVlanNetworkRequest, opts ...grpc.CallOption) (*DeleteVlanNetworkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteVlanNetworkResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_DeleteVlanNetwork_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) CreateEgressGateway(ctx context.Context, in *CreateEgressGatewayRequest, opts ...grpc.CallOption) (*CreateEgressGatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateEgressGatewayResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_CreateEgressGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) GetEgressGateway(ctx context.Context, in *GetEgressGatewayRequest, opts ...grpc.CallOption) (*GetEgressGatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEgressGatewayResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_GetEgressGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) ListEgressGateways(ctx context.Context, in *ListEgressGatewaysRequest, opts ...grpc.CallOption) (*ListEgressGatewaysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListEgressGatewaysResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_ListEgressGateways_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) DeleteEgressGateway(ctx context.Context, in *DeleteEgressGatewayRequest, opts ...grpc.CallOption) (*DeleteEgressGatewayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEgressGatewayResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_DeleteEgressGateway_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) CreatePublicAddressPool(ctx context.Context, in *CreatePublicAddressPoolRequest, opts ...grpc.CallOption) (*CreatePublicAddressPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePublicAddressPoolResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_CreatePublicAddressPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) GetPublicAddressPool(ctx context.Context, in *GetPublicAddressPoolRequest, opts ...grpc.CallOption) (*GetPublicAddressPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublicAddressPoolResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_GetPublicAddressPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) ListPublicAddressPools(ctx context.Context, in *ListPublicAddressPoolsRequest, opts ...grpc.CallOption) (*ListPublicAddressPoolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPublicAddressPoolsResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_ListPublicAddressPools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) DeletePublicAddressPool(ctx context.Context, in *DeletePublicAddressPoolRequest, opts ...grpc.CallOption) (*DeletePublicAddressPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePublicAddressPoolResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_DeletePublicAddressPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) RecordPublicPoolVerification(ctx context.Context, in *RecordPublicPoolVerificationRequest, opts ...grpc.CallOption) (*RecordPublicPoolVerificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordPublicPoolVerificationResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_RecordPublicPoolVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) SetPublicPoolAllocationEnabled(ctx context.Context, in *SetPublicPoolAllocationEnabledRequest, opts ...grpc.CallOption) (*SetPublicPoolAllocationEnabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPublicPoolAllocationEnabledResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_SetPublicPoolAllocationEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) SetDefaultPublicPool(ctx context.Context, in *SetDefaultPublicPoolRequest, opts ...grpc.CallOption) (*SetDefaultPublicPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDefaultPublicPoolResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_SetDefaultPublicPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) CreateIntranetAddressPool(ctx context.Context, in *CreateIntranetAddressPoolRequest, opts ...grpc.CallOption) (*CreateIntranetAddressPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateIntranetAddressPoolResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_CreateIntranetAddressPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) GetIntranetAddressPool(ctx context.Context, in *GetIntranetAddressPoolRequest, opts ...grpc.CallOption) (*GetIntranetAddressPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIntranetAddressPoolResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_GetIntranetAddressPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) ListIntranetAddressPools(ctx context.Context, in *ListIntranetAddressPoolsRequest, opts ...grpc.CallOption) (*ListIntranetAddressPoolsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIntranetAddressPoolsResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_ListIntranetAddressPools_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) DeleteIntranetAddressPool(ctx context.Context, in *DeleteIntranetAddressPoolRequest, opts ...grpc.CallOption) (*DeleteIntranetAddressPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteIntranetAddressPoolResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_DeleteIntranetAddressPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) RecordIntranetPoolVerification(ctx context.Context, in *RecordIntranetPoolVerificationRequest, opts ...grpc.CallOption) (*RecordIntranetPoolVerificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordIntranetPoolVerificationResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_RecordIntranetPoolVerification_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) SetIntranetPoolAllocationEnabled(ctx context.Context, in *SetIntranetPoolAllocationEnabledRequest, opts ...grpc.CallOption) (*SetIntranetPoolAllocationEnabledResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetIntranetPoolAllocationEnabledResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_SetIntranetPoolAllocationEnabled_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) SetDefaultIntranetPool(ctx context.Context, in *SetDefaultIntranetPoolRequest, opts ...grpc.CallOption) (*SetDefaultIntranetPoolResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetDefaultIntranetPoolResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_SetDefaultIntranetPool_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) GetPlatformNetworkCapabilities(ctx context.Context, in *GetPlatformNetworkCapabilitiesRequest, opts ...grpc.CallOption) (*GetPlatformNetworkCapabilitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlatformNetworkCapabilitiesResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_GetPlatformNetworkCapabilities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *platformNetworkServiceClient) GetPlatformOperation(ctx context.Context, in *GetPlatformOperationRequest, opts ...grpc.CallOption) (*GetPlatformOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPlatformOperationResponse)
	err := c.cc.Invoke(ctx, PlatformNetworkService_GetPlatformOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlatformNetworkServiceServer is the server API for PlatformNetworkService service.
// All implementations must embed UnimplementedPlatformNetworkServiceServer
// for forward compatibility.
//
// Separate platform scope, with no fictitious tenant. Management authorization
// does not automatically grant permission to act for a tenant.
type PlatformNetworkServiceServer interface {
	ListNodeInterfaces(context.Context, *ListNodeInterfacesRequest) (*ListNodeInterfacesResponse, error)
	AdoptNetworkDevice(context.Context, *AdoptNetworkDeviceRequest) (*AdoptNetworkDeviceResponse, error)
	GetNetworkDevice(context.Context, *GetNetworkDeviceRequest) (*GetNetworkDeviceResponse, error)
	CreateVlanNetwork(context.Context, *CreateVlanNetworkRequest) (*CreateVlanNetworkResponse, error)
	GetVlanNetwork(context.Context, *GetVlanNetworkRequest) (*GetVlanNetworkResponse, error)
	ListVlanNetworks(context.Context, *ListVlanNetworksRequest) (*ListVlanNetworksResponse, error)
	DeleteVlanNetwork(context.Context, *DeleteVlanNetworkRequest) (*DeleteVlanNetworkResponse, error)
	CreateEgressGateway(context.Context, *CreateEgressGatewayRequest) (*CreateEgressGatewayResponse, error)
	GetEgressGateway(context.Context, *GetEgressGatewayRequest) (*GetEgressGatewayResponse, error)
	ListEgressGateways(context.Context, *ListEgressGatewaysRequest) (*ListEgressGatewaysResponse, error)
	DeleteEgressGateway(context.Context, *DeleteEgressGatewayRequest) (*DeleteEgressGatewayResponse, error)
	CreatePublicAddressPool(context.Context, *CreatePublicAddressPoolRequest) (*CreatePublicAddressPoolResponse, error)
	GetPublicAddressPool(context.Context, *GetPublicAddressPoolRequest) (*GetPublicAddressPoolResponse, error)
	ListPublicAddressPools(context.Context, *ListPublicAddressPoolsRequest) (*ListPublicAddressPoolsResponse, error)
	DeletePublicAddressPool(context.Context, *DeletePublicAddressPoolRequest) (*DeletePublicAddressPoolResponse, error)
	RecordPublicPoolVerification(context.Context, *RecordPublicPoolVerificationRequest) (*RecordPublicPoolVerificationResponse, error)
	SetPublicPoolAllocationEnabled(context.Context, *SetPublicPoolAllocationEnabledRequest) (*SetPublicPoolAllocationEnabledResponse, error)
	SetDefaultPublicPool(context.Context, *SetDefaultPublicPoolRequest) (*SetDefaultPublicPoolResponse, error)
	CreateIntranetAddressPool(context.Context, *CreateIntranetAddressPoolRequest) (*CreateIntranetAddressPoolResponse, error)
	GetIntranetAddressPool(context.Context, *GetIntranetAddressPoolRequest) (*GetIntranetAddressPoolResponse, error)
	ListIntranetAddressPools(context.Context, *ListIntranetAddressPoolsRequest) (*ListIntranetAddressPoolsResponse, error)
	DeleteIntranetAddressPool(context.Context, *DeleteIntranetAddressPoolRequest) (*DeleteIntranetAddressPoolResponse, error)
	RecordIntranetPoolVerification(context.Context, *RecordIntranetPoolVerificationRequest) (*RecordIntranetPoolVerificationResponse, error)
	SetIntranetPoolAllocationEnabled(context.Context, *SetIntranetPoolAllocationEnabledRequest) (*SetIntranetPoolAllocationEnabledResponse, error)
	SetDefaultIntranetPool(context.Context, *SetDefaultIntranetPoolRequest) (*SetDefaultIntranetPoolResponse, error)
	GetPlatformNetworkCapabilities(context.Context, *GetPlatformNetworkCapabilitiesRequest) (*GetPlatformNetworkCapabilitiesResponse, error)
	GetPlatformOperation(context.Context, *GetPlatformOperationRequest) (*GetPlatformOperationResponse, error)
	mustEmbedUnimplementedPlatformNetworkServiceServer()
}

// UnimplementedPlatformNetworkServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPlatformNetworkServiceServer struct{}

func (UnimplementedPlatformNetworkServiceServer) ListNodeInterfaces(context.Context, *ListNodeInterfacesRequest) (*ListNodeInterfacesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListNodeInterfaces not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) AdoptNetworkDevice(context.Context, *AdoptNetworkDeviceRequest) (*AdoptNetworkDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdoptNetworkDevice not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) GetNetworkDevice(context.Context, *GetNetworkDeviceRequest) (*GetNetworkDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNetworkDevice not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) CreateVlanNetwork(context.Context, *CreateVlanNetworkRequest) (*CreateVlanNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateVlanNetwork not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) GetVlanNetwork(context.Context, *GetVlanNetworkRequest) (*GetVlanNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetVlanNetwork not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) ListVlanNetworks(context.Context, *ListVlanNetworksRequest) (*ListVlanNetworksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVlanNetworks not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) DeleteVlanNetwork(context.Context, *DeleteVlanNetworkRequest) (*DeleteVlanNetworkResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteVlanNetwork not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) CreateEgressGateway(context.Context, *CreateEgressGatewayRequest) (*CreateEgressGatewayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateEgressGateway not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) GetEgressGateway(context.Context, *GetEgressGatewayRequest) (*GetEgressGatewayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEgressGateway not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) ListEgressGateways(context.Context, *ListEgressGatewaysRequest) (*ListEgressGatewaysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListEgressGateways not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) DeleteEgressGateway(context.Context, *DeleteEgressGatewayRequest) (*DeleteEgressGatewayResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEgressGateway not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) CreatePublicAddressPool(context.Context, *CreatePublicAddressPoolRequest) (*CreatePublicAddressPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePublicAddressPool not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) GetPublicAddressPool(context.Context, *GetPublicAddressPoolRequest) (*GetPublicAddressPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublicAddressPool not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) ListPublicAddressPools(context.Context, *ListPublicAddressPoolsRequest) (*ListPublicAddressPoolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPublicAddressPools not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) DeletePublicAddressPool(context.Context, *DeletePublicAddressPoolRequest) (*DeletePublicAddressPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePublicAddressPool not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) RecordPublicPoolVerification(context.Context, *RecordPublicPoolVerificationRequest) (*RecordPublicPoolVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordPublicPoolVerification not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) SetPublicPoolAllocationEnabled(context.Context, *SetPublicPoolAllocationEnabledRequest) (*SetPublicPoolAllocationEnabledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetPublicPoolAllocationEnabled not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) SetDefaultPublicPool(context.Context, *SetDefaultPublicPoolRequest) (*SetDefaultPublicPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDefaultPublicPool not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) CreateIntranetAddressPool(context.Context, *CreateIntranetAddressPoolRequest) (*CreateIntranetAddressPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIntranetAddressPool not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) GetIntranetAddressPool(context.Context, *GetIntranetAddressPoolRequest) (*GetIntranetAddressPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIntranetAddressPool not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) ListIntranetAddressPools(context.Context, *ListIntranetAddressPoolsRequest) (*ListIntranetAddressPoolsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIntranetAddressPools not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) DeleteIntranetAddressPool(context.Context, *DeleteIntranetAddressPoolRequest) (*DeleteIntranetAddressPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIntranetAddressPool not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) RecordIntranetPoolVerification(context.Context, *RecordIntranetPoolVerificationRequest) (*RecordIntranetPoolVerificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordIntranetPoolVerification not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) SetIntranetPoolAllocationEnabled(context.Context, *SetIntranetPoolAllocationEnabledRequest) (*SetIntranetPoolAllocationEnabledResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetIntranetPoolAllocationEnabled not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) SetDefaultIntranetPool(context.Context, *SetDefaultIntranetPoolRequest) (*SetDefaultIntranetPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDefaultIntranetPool not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) GetPlatformNetworkCapabilities(context.Context, *GetPlatformNetworkCapabilitiesRequest) (*GetPlatformNetworkCapabilitiesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlatformNetworkCapabilities not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) GetPlatformOperation(context.Context, *GetPlatformOperationRequest) (*GetPlatformOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPlatformOperation not implemented")
}
func (UnimplementedPlatformNetworkServiceServer) mustEmbedUnimplementedPlatformNetworkServiceServer() {
}
func (UnimplementedPlatformNetworkServiceServer) testEmbeddedByValue() {}

// UnsafePlatformNetworkServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PlatformNetworkServiceServer will
// result in compilation errors.
type UnsafePlatformNetworkServiceServer interface {
	mustEmbedUnimplementedPlatformNetworkServiceServer()
}

func RegisterPlatformNetworkServiceServer(s grpc.ServiceRegistrar, srv PlatformNetworkServiceServer) {
	// If the following call pancis, it indicates UnimplementedPlatformNetworkServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PlatformNetworkService_ServiceDesc, srv)
}

func _PlatformNetworkService_ListNodeInterfaces_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNodeInterfacesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).ListNodeInterfaces(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_ListNodeInterfaces_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).ListNodeInterfaces(ctx, req.(*ListNodeInterfacesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_AdoptNetworkDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdoptNetworkDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).AdoptNetworkDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_AdoptNetworkDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).AdoptNetworkDevice(ctx, req.(*AdoptNetworkDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_GetNetworkDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNetworkDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).GetNetworkDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_GetNetworkDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).GetNetworkDevice(ctx, req.(*GetNetworkDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_CreateVlanNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVlanNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).CreateVlanNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_CreateVlanNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).CreateVlanNetwork(ctx, req.(*CreateVlanNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_GetVlanNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetVlanNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).GetVlanNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_GetVlanNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).GetVlanNetwork(ctx, req.(*GetVlanNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_ListVlanNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVlanNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).ListVlanNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_ListVlanNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).ListVlanNetworks(ctx, req.(*ListVlanNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_DeleteVlanNetwork_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteVlanNetworkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).DeleteVlanNetwork(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_DeleteVlanNetwork_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).DeleteVlanNetwork(ctx, req.(*DeleteVlanNetworkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_CreateEgressGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateEgressGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).CreateEgressGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_CreateEgressGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).CreateEgressGateway(ctx, req.(*CreateEgressGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_GetEgressGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEgressGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).GetEgressGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_GetEgressGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).GetEgressGateway(ctx, req.(*GetEgressGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_ListEgressGateways_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListEgressGatewaysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).ListEgressGateways(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_ListEgressGateways_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).ListEgressGateways(ctx, req.(*ListEgressGatewaysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_DeleteEgressGateway_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEgressGatewayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).DeleteEgressGateway(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_DeleteEgressGateway_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).DeleteEgressGateway(ctx, req.(*DeleteEgressGatewayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_CreatePublicAddressPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePublicAddressPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).CreatePublicAddressPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_CreatePublicAddressPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).CreatePublicAddressPool(ctx, req.(*CreatePublicAddressPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_GetPublicAddressPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublicAddressPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).GetPublicAddressPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_GetPublicAddressPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).GetPublicAddressPool(ctx, req.(*GetPublicAddressPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_ListPublicAddressPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPublicAddressPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).ListPublicAddressPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_ListPublicAddressPools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).ListPublicAddressPools(ctx, req.(*ListPublicAddressPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_DeletePublicAddressPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePublicAddressPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).DeletePublicAddressPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_DeletePublicAddressPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).DeletePublicAddressPool(ctx, req.(*DeletePublicAddressPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_RecordPublicPoolVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordPublicPoolVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).RecordPublicPoolVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_RecordPublicPoolVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).RecordPublicPoolVerification(ctx, req.(*RecordPublicPoolVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_SetPublicPoolAllocationEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPublicPoolAllocationEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).SetPublicPoolAllocationEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_SetPublicPoolAllocationEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).SetPublicPoolAllocationEnabled(ctx, req.(*SetPublicPoolAllocationEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_SetDefaultPublicPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultPublicPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).SetDefaultPublicPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_SetDefaultPublicPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).SetDefaultPublicPool(ctx, req.(*SetDefaultPublicPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_CreateIntranetAddressPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIntranetAddressPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).CreateIntranetAddressPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_CreateIntranetAddressPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).CreateIntranetAddressPool(ctx, req.(*CreateIntranetAddressPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_GetIntranetAddressPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIntranetAddressPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).GetIntranetAddressPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_GetIntranetAddressPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).GetIntranetAddressPool(ctx, req.(*GetIntranetAddressPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_ListIntranetAddressPools_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIntranetAddressPoolsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).ListIntranetAddressPools(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_ListIntranetAddressPools_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).ListIntranetAddressPools(ctx, req.(*ListIntranetAddressPoolsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_DeleteIntranetAddressPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIntranetAddressPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).DeleteIntranetAddressPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_DeleteIntranetAddressPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).DeleteIntranetAddressPool(ctx, req.(*DeleteIntranetAddressPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_RecordIntranetPoolVerification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordIntranetPoolVerificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).RecordIntranetPoolVerification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_RecordIntranetPoolVerification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).RecordIntranetPoolVerification(ctx, req.(*RecordIntranetPoolVerificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_SetIntranetPoolAllocationEnabled_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetIntranetPoolAllocationEnabledRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).SetIntranetPoolAllocationEnabled(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_SetIntranetPoolAllocationEnabled_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).SetIntranetPoolAllocationEnabled(ctx, req.(*SetIntranetPoolAllocationEnabledRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_SetDefaultIntranetPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetDefaultIntranetPoolRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).SetDefaultIntranetPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_SetDefaultIntranetPool_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).SetDefaultIntranetPool(ctx, req.(*SetDefaultIntranetPoolRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_GetPlatformNetworkCapabilities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlatformNetworkCapabilitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).GetPlatformNetworkCapabilities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_GetPlatformNetworkCapabilities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).GetPlatformNetworkCapabilities(ctx, req.(*GetPlatformNetworkCapabilitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PlatformNetworkService_GetPlatformOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPlatformOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlatformNetworkServiceServer).GetPlatformOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PlatformNetworkService_GetPlatformOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlatformNetworkServiceServer).GetPlatformOperation(ctx, req.(*GetPlatformOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PlatformNetworkService_ServiceDesc is the grpc.ServiceDesc for PlatformNetworkService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PlatformNetworkService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "network.v1.PlatformNetworkService",
	HandlerType: (*PlatformNetworkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListNodeInterfaces",
			Handler:    _PlatformNetworkService_ListNodeInterfaces_Handler,
		},
		{
			MethodName: "AdoptNetworkDevice",
			Handler:    _PlatformNetworkService_AdoptNetworkDevice_Handler,
		},
		{
			MethodName: "GetNetworkDevice",
			Handler:    _PlatformNetworkService_GetNetworkDevice_Handler,
		},
		{
			MethodName: "CreateVlanNetwork",
			Handler:    _PlatformNetworkService_CreateVlanNetwork_Handler,
		},
		{
			MethodName: "GetVlanNetwork",
			Handler:    _PlatformNetworkService_GetVlanNetwork_Handler,
		},
		{
			MethodName: "ListVlanNetworks",
			Handler:    _PlatformNetworkService_ListVlanNetworks_Handler,
		},
		{
			MethodName: "DeleteVlanNetwork",
			Handler:    _PlatformNetworkService_DeleteVlanNetwork_Handler,
		},
		{
			MethodName: "CreateEgressGateway",
			Handler:    _PlatformNetworkService_CreateEgressGateway_Handler,
		},
		{
			MethodName: "GetEgressGateway",
			Handler:    _PlatformNetworkService_GetEgressGateway_Handler,
		},
		{
			MethodName: "ListEgressGateways",
			Handler:    _PlatformNetworkService_ListEgressGateways_Handler,
		},
		{
			MethodName: "DeleteEgressGateway",
			Handler:    _PlatformNetworkService_DeleteEgressGateway_Handler,
		},
		{
			MethodName: "CreatePublicAddressPool",
			Handler:    _PlatformNetworkService_CreatePublicAddressPool_Handler,
		},
		{
			MethodName: "GetPublicAddressPool",
			Handler:    _PlatformNetworkService_GetPublicAddressPool_Handler,
		},
		{
			MethodName: "ListPublicAddressPools",
			Handler:    _PlatformNetworkService_ListPublicAddressPools_Handler,
		},
		{
			MethodName: "DeletePublicAddressPool",
			Handler:    _PlatformNetworkService_DeletePublicAddressPool_Handler,
		},
		{
			MethodName: "RecordPublicPoolVerification",
			Handler:    _PlatformNetworkService_RecordPublicPoolVerification_Handler,
		},
		{
			MethodName: "SetPublicPoolAllocationEnabled",
			Handler:    _PlatformNetworkService_SetPublicPoolAllocationEnabled_Handler,
		},
		{
			MethodName: "SetDefaultPublicPool",
			Handler:    _PlatformNetworkService_SetDefaultPublicPool_Handler,
		},
		{
			MethodName: "CreateIntranetAddressPool",
			Handler:    _PlatformNetworkService_CreateIntranetAddressPool_Handler,
		},
		{
			MethodName: "GetIntranetAddressPool",
			Handler:    _PlatformNetworkService_GetIntranetAddressPool_Handler,
		},
		{
			MethodName: "ListIntranetAddressPools",
			Handler:    _PlatformNetworkService_ListIntranetAddressPools_Handler,
		},
		{
			MethodName: "DeleteIntranetAddressPool",
			Handler:    _PlatformNetworkService_DeleteIntranetAddressPool_Handler,
		},
		{
			MethodName: "RecordIntranetPoolVerification",
			Handler:    _PlatformNetworkService_RecordIntranetPoolVerification_Handler,
		},
		{
			MethodName: "SetIntranetPoolAllocationEnabled",
			Handler:    _PlatformNetworkService_SetIntranetPoolAllocationEnabled_Handler,
		},
		{
			MethodName: "SetDefaultIntranetPool",
			Handler:    _PlatformNetworkService_SetDefaultIntranetPool_Handler,
		},
		{
			MethodName: "GetPlatformNetworkCapabilities",
			Handler:    _PlatformNetworkService_GetPlatformNetworkCapabilities_Handler,
		},
		{
			MethodName: "GetPlatformOperation",
			Handler:    _PlatformNetworkService_GetPlatformOperation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "network/v1/egress.proto",
}
