// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: network/v1/load_balancer.proto

package networkv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TenantLoadBalancerService_CreateLoadBalancer_FullMethodName       = "/network.v1.TenantLoadBalancerService/CreateLoadBalancer"
	TenantLoadBalancerService_GetLoadBalancer_FullMethodName          = "/network.v1.TenantLoadBalancerService/GetLoadBalancer"
	TenantLoadBalancerService_ListLoadBalancers_FullMethodName        = "/network.v1.TenantLoadBalancerService/ListLoadBalancers"
	TenantLoadBalancerService_UpdateLoadBalancer_FullMethodName       = "/network.v1.TenantLoadBalancerService/UpdateLoadBalancer"
	TenantLoadBalancerService_DeleteLoadBalancer_FullMethodName       = "/network.v1.TenantLoadBalancerService/DeleteLoadBalancer"
	TenantLoadBalancerService_GetLoadBalancerOperation_FullMethodName = "/network.v1.TenantLoadBalancerService/GetLoadBalancerOperation"
)

// TenantLoadBalancerServiceClient is the client API for TenantLoadBalancerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// NET-U00 contract reservation. NET-VPC-BASE-01 does not register this service,
// accept LB operations, or implement LB Provider behavior. NET-U05/U06 must meet
// their separate gates before registration. No request accepts Provider YAML,
// namespace, cluster placement, GatewayClass, image or Kubernetes annotations.
// target_tenant_id follows TenantEgressService's trusted-context/delegation rule;
// it is never accepted as proof of tenant identity or authorization.
type TenantLoadBalancerServiceClient interface {
	CreateLoadBalancer(ctx context.Context, in *CreateLoadBalancerRequest, opts ...grpc.CallOption) (*CreateLoadBalancerResponse, error)
	GetLoadBalancer(ctx context.Context, in *GetLoadBalancerRequest, opts ...grpc.CallOption) (*GetLoadBalancerResponse, error)
	ListLoadBalancers(ctx context.Context, in *ListLoadBalancersRequest, opts ...grpc.CallOption) (*ListLoadBalancersResponse, error)
	UpdateLoadBalancer(ctx context.Context, in *UpdateLoadBalancerRequest, opts ...grpc.CallOption) (*UpdateLoadBalancerResponse, error)
	DeleteLoadBalancer(ctx context.Context, in *DeleteLoadBalancerRequest, opts ...grpc.CallOption) (*DeleteLoadBalancerResponse, error)
	GetLoadBalancerOperation(ctx context.Context, in *GetLoadBalancerOperationRequest, opts ...grpc.CallOption) (*GetLoadBalancerOperationResponse, error)
}

type tenantLoadBalancerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantLoadBalancerServiceClient(cc grpc.ClientConnInterface) TenantLoadBalancerServiceClient {
	return &tenantLoadBalancerServiceClient{cc}
}

func (c *tenantLoadBalancerServiceClient) CreateLoadBalancer(ctx context.Context, in *CreateLoadBalancerRequest, opts ...grpc.CallOption) (*CreateLoadBalancerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLoadBalancerResponse)
	err := c.cc.Invoke(ctx, TenantLoadBalancerService_CreateLoadBalancer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantLoadBalancerServiceClient) GetLoadBalancer(ctx context.Context, in *GetLoadBalancerRequest, opts ...grpc.CallOption) (*GetLoadBalancerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoadBalancerResponse)
	err := c.cc.Invoke(ctx, TenantLoadBalancerService_GetLoadBalancer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantLoadBalancerServiceClient) ListLoadBalancers(ctx context.Context, in *ListLoadBalancersRequest, opts ...grpc.CallOption) (*ListLoadBalancersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLoadBalancersResponse)
	err := c.cc.Invoke(ctx, TenantLoadBalancerService_ListLoadBalancers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantLoadBalancerServiceClient) UpdateLoadBalancer(ctx context.Context, in *UpdateLoadBalancerRequest, opts ...grpc.CallOption) (*UpdateLoadBalancerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLoadBalancerResponse)
	err := c.cc.Invoke(ctx, TenantLoadBalancerService_UpdateLoadBalancer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantLoadBalancerServiceClient) DeleteLoadBalancer(ctx context.Context, in *DeleteLoadBalancerRequest, opts ...grpc.CallOption) (*DeleteLoadBalancerResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLoadBalancerResponse)
	err := c.cc.Invoke(ctx, TenantLoadBalancerService_DeleteLoadBalancer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantLoadBalancerServiceClient) GetLoadBalancerOperation(ctx context.Context, in *GetLoadBalancerOperationRequest, opts ...grpc.CallOption) (*GetLoadBalancerOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLoadBalancerOperationResponse)
	err := c.cc.Invoke(ctx, TenantLoadBalancerService_GetLoadBalancerOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantLoadBalancerServiceServer is the server API for TenantLoadBalancerService service.
// All implementations must embed UnimplementedTenantLoadBalancerServiceServer
// for forward compatibility.
//
// NET-U00 contract reservation. NET-VPC-BASE-01 does not register this service,
// accept LB operations, or implement LB Provider behavior. NET-U05/U06 must meet
// their separate gates before registration. No request accepts Provider YAML,
// namespace, cluster placement, GatewayClass, image or Kubernetes annotations.
// target_tenant_id follows TenantEgressService's trusted-context/delegation rule;
// it is never accepted as proof of tenant identity or authorization.
type TenantLoadBalancerServiceServer interface {
	CreateLoadBalancer(context.Context, *CreateLoadBalancerRequest) (*CreateLoadBalancerResponse, error)
	GetLoadBalancer(context.Context, *GetLoadBalancerRequest) (*GetLoadBalancerResponse, error)
	ListLoadBalancers(context.Context, *ListLoadBalancersRequest) (*ListLoadBalancersResponse, error)
	UpdateLoadBalancer(context.Context, *UpdateLoadBalancerRequest) (*UpdateLoadBalancerResponse, error)
	DeleteLoadBalancer(context.Context, *DeleteLoadBalancerRequest) (*DeleteLoadBalancerResponse, error)
	GetLoadBalancerOperation(context.Context, *GetLoadBalancerOperationRequest) (*GetLoadBalancerOperationResponse, error)
	mustEmbedUnimplementedTenantLoadBalancerServiceServer()
}

// UnimplementedTenantLoadBalancerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTenantLoadBalancerServiceServer struct{}

func (UnimplementedTenantLoadBalancerServiceServer) CreateLoadBalancer(context.Context, *CreateLoadBalancerRequest) (*CreateLoadBalancerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateLoadBalancer not implemented")
}
func (UnimplementedTenantLoadBalancerServiceServer) GetLoadBalancer(context.Context, *GetLoadBalancerRequest) (*GetLoadBalancerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoadBalancer not implemented")
}
func (UnimplementedTenantLoadBalancerServiceServer) ListLoadBalancers(context.Context, *ListLoadBalancersRequest) (*ListLoadBalancersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListLoadBalancers not implemented")
}
func (UnimplementedTenantLoadBalancerServiceServer) UpdateLoadBalancer(context.Context, *UpdateLoadBalancerRequest) (*UpdateLoadBalancerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateLoadBalancer not implemented")
}
func (UnimplementedTenantLoadBalancerServiceServer) DeleteLoadBalancer(context.Context, *DeleteLoadBalancerRequest) (*DeleteLoadBalancerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLoadBalancer not implemented")
}
func (UnimplementedTenantLoadBalancerServiceServer) GetLoadBalancerOperation(context.Context, *GetLoadBalancerOperationRequest) (*GetLoadBalancerOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLoadBalancerOperation not implemented")
}
func (UnimplementedTenantLoadBalancerServiceServer) mustEmbedUnimplementedTenantLoadBalancerServiceServer() {
}
func (UnimplementedTenantLoadBalancerServiceServer) testEmbeddedByValue() {}

// UnsafeTenantLoadBalancerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantLoadBalancerServiceServer will
// result in compilation errors.
type UnsafeTenantLoadBalancerServiceServer interface {
	mustEmbedUnimplementedTenantLoadBalancerServiceServer()
}

func RegisterTenantLoadBalancerServiceServer(s grpc.ServiceRegistrar, srv TenantLoadBalancerServiceServer) {
	// If the following call pancis, it indicates UnimplementedTenantLoadBalancerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TenantLoadBalancerService_ServiceDesc, srv)
}

func _TenantLoadBalancerService_CreateLoadBalancer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLoadBalancerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantLoadBalancerServiceServer).CreateLoadBalancer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantLoadBalancerService_CreateLoadBalancer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantLoadBalancerServiceServer).CreateLoadBalancer(ctx, req.(*CreateLoadBalancerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantLoadBalancerService_GetLoadBalancer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoadBalancerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantLoadBalancerServiceServer).GetLoadBalancer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantLoadBalancerService_GetLoadBalancer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantLoadBalancerServiceServer).GetLoadBalancer(ctx, req.(*GetLoadBalancerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantLoadBalancerService_ListLoadBalancers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLoadBalancersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantLoadBalancerServiceServer).ListLoadBalancers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantLoadBalancerService_ListLoadBalancers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantLoadBalancerServiceServer).ListLoadBalancers(ctx, req.(*ListLoadBalancersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantLoadBalancerService_UpdateLoadBalancer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLoadBalancerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantLoadBalancerServiceServer).UpdateLoadBalancer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantLoadBalancerService_UpdateLoadBalancer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantLoadBalancerServiceServer).UpdateLoadBalancer(ctx, req.(*UpdateLoadBalancerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantLoadBalancerService_DeleteLoadBalancer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLoadBalancerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantLoadBalancerServiceServer).DeleteLoadBalancer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantLoadBalancerService_DeleteLoadBalancer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantLoadBalancerServiceServer).DeleteLoadBalancer(ctx, req.(*DeleteLoadBalancerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantLoadBalancerService_GetLoadBalancerOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLoadBalancerOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantLoadBalancerServiceServer).GetLoadBalancerOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantLoadBalancerService_GetLoadBalancerOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantLoadBalancerServiceServer).GetLoadBalancerOperation(ctx, req.(*GetLoadBalancerOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TenantLoadBalancerService_ServiceDesc is the grpc.ServiceDesc for TenantLoadBalancerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TenantLoadBalancerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "network.v1.TenantLoadBalancerService",
	HandlerType: (*TenantLoadBalancerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLoadBalancer",
			Handler:    _TenantLoadBalancerService_CreateLoadBalancer_Handler,
		},
		{
			MethodName: "GetLoadBalancer",
			Handler:    _TenantLoadBalancerService_GetLoadBalancer_Handler,
		},
		{
			MethodName: "ListLoadBalancers",
			Handler:    _TenantLoadBalancerService_ListLoadBalancers_Handler,
		},
		{
			MethodName: "UpdateLoadBalancer",
			Handler:    _TenantLoadBalancerService_UpdateLoadBalancer_Handler,
		},
		{
			MethodName: "DeleteLoadBalancer",
			Handler:    _TenantLoadBalancerService_DeleteLoadBalancer_Handler,
		},
		{
			MethodName: "GetLoadBalancerOperation",
			Handler:    _TenantLoadBalancerService_GetLoadBalancerOperation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "network/v1/load_balancer.proto",
}
