// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: network/v1/network.proto

package networkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResourceState int32

const (
	ResourceState_RESOURCE_STATE_UNSPECIFIED  ResourceState = 0
	ResourceState_RESOURCE_STATE_PROVISIONING ResourceState = 1
	ResourceState_RESOURCE_STATE_AVAILABLE    ResourceState = 2
	ResourceState_RESOURCE_STATE_DEGRADED     ResourceState = 3
	ResourceState_RESOURCE_STATE_FAILED       ResourceState = 4
	ResourceState_RESOURCE_STATE_DELETING     ResourceState = 5
	ResourceState_RESOURCE_STATE_DELETED      ResourceState = 6
)

// Enum value maps for ResourceState.
var (
	ResourceState_name = map[int32]string{
		0: "RESOURCE_STATE_UNSPECIFIED",
		1: "RESOURCE_STATE_PROVISIONING",
		2: "RESOURCE_STATE_AVAILABLE",
		3: "RESOURCE_STATE_DEGRADED",
		4: "RESOURCE_STATE_FAILED",
		5: "RESOURCE_STATE_DELETING",
		6: "RESOURCE_STATE_DELETED",
	}
	ResourceState_value = map[string]int32{
		"RESOURCE_STATE_UNSPECIFIED":  0,
		"RESOURCE_STATE_PROVISIONING": 1,
		"RESOURCE_STATE_AVAILABLE":    2,
		"RESOURCE_STATE_DEGRADED":     3,
		"RESOURCE_STATE_FAILED":       4,
		"RESOURCE_STATE_DELETING":     5,
		"RESOURCE_STATE_DELETED":      6,
	}
)

func (x ResourceState) Enum() *ResourceState {
	p := new(ResourceState)
	*p = x
	return p
}

func (x ResourceState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceState) Descriptor() protoreflect.EnumDescriptor {
	return file_network_v1_network_proto_enumTypes[0].Descriptor()
}

func (ResourceState) Type() protoreflect.EnumType {
	return &file_network_v1_network_proto_enumTypes[0]
}

func (x ResourceState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceState.Descriptor instead.
func (ResourceState) EnumDescriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{0}
}

type OperationState int32

const (
	OperationState_OPERATION_STATE_UNSPECIFIED OperationState = 0
	OperationState_OPERATION_STATE_QUEUED      OperationState = 1
	OperationState_OPERATION_STATE_RUNNING     OperationState = 2
	OperationState_OPERATION_STATE_RETRYING    OperationState = 3
	OperationState_OPERATION_STATE_BLOCKED     OperationState = 4
	OperationState_OPERATION_STATE_SUCCEEDED   OperationState = 5
	OperationState_OPERATION_STATE_FAILED      OperationState = 6
)

// Enum value maps for OperationState.
var (
	OperationState_name = map[int32]string{
		0: "OPERATION_STATE_UNSPECIFIED",
		1: "OPERATION_STATE_QUEUED",
		2: "OPERATION_STATE_RUNNING",
		3: "OPERATION_STATE_RETRYING",
		4: "OPERATION_STATE_BLOCKED",
		5: "OPERATION_STATE_SUCCEEDED",
		6: "OPERATION_STATE_FAILED",
	}
	OperationState_value = map[string]int32{
		"OPERATION_STATE_UNSPECIFIED": 0,
		"OPERATION_STATE_QUEUED":      1,
		"OPERATION_STATE_RUNNING":     2,
		"OPERATION_STATE_RETRYING":    3,
		"OPERATION_STATE_BLOCKED":     4,
		"OPERATION_STATE_SUCCEEDED":   5,
		"OPERATION_STATE_FAILED":      6,
	}
)

func (x OperationState) Enum() *OperationState {
	p := new(OperationState)
	*p = x
	return p
}

func (x OperationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationState) Descriptor() protoreflect.EnumDescriptor {
	return file_network_v1_network_proto_enumTypes[1].Descriptor()
}

func (OperationState) Type() protoreflect.EnumType {
	return &file_network_v1_network_proto_enumTypes[1]
}

func (x OperationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationState.Descriptor instead.
func (OperationState) EnumDescriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{1}
}

type OperationKind int32

const (
	OperationKind_OPERATION_KIND_UNSPECIFIED OperationKind = 0
	OperationKind_OPERATION_KIND_CREATE_VPC  OperationKind = 1
	OperationKind_OPERATION_KIND_DELETE_VPC  OperationKind = 2
)

// Enum value maps for OperationKind.
var (
	OperationKind_name = map[int32]string{
		0: "OPERATION_KIND_UNSPECIFIED",
		1: "OPERATION_KIND_CREATE_VPC",
		2: "OPERATION_KIND_DELETE_VPC",
	}
	OperationKind_value = map[string]int32{
		"OPERATION_KIND_UNSPECIFIED": 0,
		"OPERATION_KIND_CREATE_VPC":  1,
		"OPERATION_KIND_DELETE_VPC":  2,
	}
)

func (x OperationKind) Enum() *OperationKind {
	p := new(OperationKind)
	*p = x
	return p
}

func (x OperationKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationKind) Descriptor() protoreflect.EnumDescriptor {
	return file_network_v1_network_proto_enumTypes[2].Descriptor()
}

func (OperationKind) Type() protoreflect.EnumType {
	return &file_network_v1_network_proto_enumTypes[2]
}

func (x OperationKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationKind.Descriptor instead.
func (OperationKind) EnumDescriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{2}
}

type ResourceType int32

const (
	ResourceType_RESOURCE_TYPE_UNSPECIFIED ResourceType = 0
	ResourceType_RESOURCE_TYPE_VPC         ResourceType = 1
)

// Enum value maps for ResourceType.
var (
	ResourceType_name = map[int32]string{
		0: "RESOURCE_TYPE_UNSPECIFIED",
		1: "RESOURCE_TYPE_VPC",
	}
	ResourceType_value = map[string]int32{
		"RESOURCE_TYPE_UNSPECIFIED": 0,
		"RESOURCE_TYPE_VPC":         1,
	}
)

func (x ResourceType) Enum() *ResourceType {
	p := new(ResourceType)
	*p = x
	return p
}

func (x ResourceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResourceType) Descriptor() protoreflect.EnumDescriptor {
	return file_network_v1_network_proto_enumTypes[3].Descriptor()
}

func (ResourceType) Type() protoreflect.EnumType {
	return &file_network_v1_network_proto_enumTypes[3]
}

func (x ResourceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResourceType.Descriptor instead.
func (ResourceType) EnumDescriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{3}
}

type VPC struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId         string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name             string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Cidr             string                 `protobuf:"bytes,5,opt,name=cidr,proto3" json:"cidr,omitempty"`
	State            ResourceState          `protobuf:"varint,6,opt,name=state,proto3,enum=network.v1.ResourceState" json:"state,omitempty"`
	Reason           string                 `protobuf:"bytes,7,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Version          int64                  `protobuf:"varint,10,opt,name=version,proto3" json:"version,omitempty"`
	ObservedAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	ObservationStale bool                   `protobuf:"varint,12,opt,name=observation_stale,json=observationStale,proto3" json:"observation_stale,omitempty"`
	LastOperationId  string                 `protobuf:"bytes,13,opt,name=last_operation_id,json=lastOperationId,proto3" json:"last_operation_id,omitempty"`
	// Always zero in NET-01; actual child count is delivered with NET-02.
	SubnetCount   int64  `protobuf:"varint,14,opt,name=subnet_count,json=subnetCount,proto3" json:"subnet_count,omitempty"`
	ReasonMessage string `protobuf:"bytes,15,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VPC) Reset() {
	*x = VPC{}
	mi := &file_network_v1_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VPC) ProtoMessage() {}

func (x *VPC) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VPC.ProtoReflect.Descriptor instead.
func (*VPC) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{0}
}

func (x *VPC) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VPC) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *VPC) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VPC) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *VPC) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *VPC) GetState() ResourceState {
	if x != nil {
		return x.State
	}
	return ResourceState_RESOURCE_STATE_UNSPECIFIED
}

func (x *VPC) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *VPC) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VPC) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *VPC) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VPC) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *VPC) GetObservationStale() bool {
	if x != nil {
		return x.ObservationStale
	}
	return false
}

func (x *VPC) GetLastOperationId() string {
	if x != nil {
		return x.LastOperationId
	}
	return ""
}

func (x *VPC) GetSubnetCount() int64 {
	if x != nil {
		return x.SubnetCount
	}
	return 0
}

func (x *VPC) GetReasonMessage() string {
	if x != nil {
		return x.ReasonMessage
	}
	return ""
}

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Kind          OperationKind          `protobuf:"varint,4,opt,name=kind,proto3,enum=network.v1.OperationKind" json:"kind,omitempty"`
	State         OperationState         `protobuf:"varint,5,opt,name=state,proto3,enum=network.v1.OperationState" json:"state,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CompletedAt   *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	NextAttemptAt *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=next_attempt_at,json=nextAttemptAt,proto3" json:"next_attempt_at,omitempty"`
	ResourceType  ResourceType           `protobuf:"varint,11,opt,name=resource_type,json=resourceType,proto3,enum=network.v1.ResourceType" json:"resource_type,omitempty"`
	ReasonMessage string                 `protobuf:"bytes,12,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_network_v1_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{1}
}

func (x *Operation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Operation) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Operation) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *Operation) GetKind() OperationKind {
	if x != nil {
		return x.Kind
	}
	return OperationKind_OPERATION_KIND_UNSPECIFIED
}

func (x *Operation) GetState() OperationState {
	if x != nil {
		return x.State
	}
	return OperationState_OPERATION_STATE_UNSPECIFIED
}

func (x *Operation) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Operation) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Operation) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Operation) GetCompletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletedAt
	}
	return nil
}

func (x *Operation) GetNextAttemptAt() *timestamppb.Timestamp {
	if x != nil {
		return x.NextAttemptAt
	}
	return nil
}

func (x *Operation) GetResourceType() ResourceType {
	if x != nil {
		return x.ResourceType
	}
	return ResourceType_RESOURCE_TYPE_UNSPECIFIED
}

func (x *Operation) GetReasonMessage() string {
	if x != nil {
		return x.ReasonMessage
	}
	return ""
}

// Unverified attribution; never an authenticated principal or tenant owner.
type Attribution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         string                 `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`
	DirectCaller  string                 `protobuf:"bytes,2,opt,name=direct_caller,json=directCaller,proto3" json:"direct_caller,omitempty"`
	CorrelationId string                 `protobuf:"bytes,3,opt,name=correlation_id,json=correlationId,proto3" json:"correlation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribution) Reset() {
	*x = Attribution{}
	mi := &file_network_v1_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribution) ProtoMessage() {}

func (x *Attribution) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribution.ProtoReflect.Descriptor instead.
func (*Attribution) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{2}
}

func (x *Attribution) GetActor() string {
	if x != nil {
		return x.Actor
	}
	return ""
}

func (x *Attribution) GetDirectCaller() string {
	if x != nil {
		return x.DirectCaller
	}
	return ""
}

func (x *Attribution) GetCorrelationId() string {
	if x != nil {
		return x.CorrelationId
	}
	return ""
}

type CreateVPCRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Cidr           string                 `protobuf:"bytes,3,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Attribution    *Attribution           `protobuf:"bytes,6,opt,name=attribution,proto3" json:"attribution,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateVPCRequest) Reset() {
	*x = CreateVPCRequest{}
	mi := &file_network_v1_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVPCRequest) ProtoMessage() {}

func (x *CreateVPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVPCRequest.ProtoReflect.Descriptor instead.
func (*CreateVPCRequest) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{3}
}

func (x *CreateVPCRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateVPCRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateVPCRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *CreateVPCRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateVPCRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateVPCRequest) GetAttribution() *Attribution {
	if x != nil {
		return x.Attribution
	}
	return nil
}

type CreateVPCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vpc           *VPC                   `protobuf:"bytes,1,opt,name=vpc,proto3" json:"vpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVPCResponse) Reset() {
	*x = CreateVPCResponse{}
	mi := &file_network_v1_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVPCResponse) ProtoMessage() {}

func (x *CreateVPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVPCResponse.ProtoReflect.Descriptor instead.
func (*CreateVPCResponse) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{4}
}

func (x *CreateVPCResponse) GetVpc() *VPC {
	if x != nil {
		return x.Vpc
	}
	return nil
}

type GetVPCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	VpcId         string                 `protobuf:"bytes,2,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVPCRequest) Reset() {
	*x = GetVPCRequest{}
	mi := &file_network_v1_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVPCRequest) ProtoMessage() {}

func (x *GetVPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVPCRequest.ProtoReflect.Descriptor instead.
func (*GetVPCRequest) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{5}
}

func (x *GetVPCRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetVPCRequest) GetVpcId() string {
	if x != nil {
		return x.VpcId
	}
	return ""
}

type GetVPCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vpc           *VPC                   `protobuf:"bytes,1,opt,name=vpc,proto3" json:"vpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVPCResponse) Reset() {
	*x = GetVPCResponse{}
	mi := &file_network_v1_network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVPCResponse) ProtoMessage() {}

func (x *GetVPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVPCResponse.ProtoReflect.Descriptor instead.
func (*GetVPCResponse) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{6}
}

func (x *GetVPCResponse) GetVpc() *VPC {
	if x != nil {
		return x.Vpc
	}
	return nil
}

type ListVPCsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	State         ResourceState          `protobuf:"varint,3,opt,name=state,proto3,enum=network.v1.ResourceState" json:"state,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,5,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVPCsRequest) Reset() {
	*x = ListVPCsRequest{}
	mi := &file_network_v1_network_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVPCsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVPCsRequest) ProtoMessage() {}

func (x *ListVPCsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVPCsRequest.ProtoReflect.Descriptor instead.
func (*ListVPCsRequest) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{7}
}

func (x *ListVPCsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListVPCsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListVPCsRequest) GetState() ResourceState {
	if x != nil {
		return x.State
	}
	return ResourceState_RESOURCE_STATE_UNSPECIFIED
}

func (x *ListVPCsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListVPCsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListVPCsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*VPC                 `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVPCsResponse) Reset() {
	*x = ListVPCsResponse{}
	mi := &file_network_v1_network_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVPCsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVPCsResponse) ProtoMessage() {}

func (x *ListVPCsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVPCsResponse.ProtoReflect.Descriptor instead.
func (*ListVPCsResponse) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{8}
}

func (x *ListVPCsResponse) GetItems() []*VPC {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListVPCsResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type DeleteVPCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	VpcId         string                 `protobuf:"bytes,2,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVPCRequest) Reset() {
	*x = DeleteVPCRequest{}
	mi := &file_network_v1_network_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVPCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVPCRequest) ProtoMessage() {}

func (x *DeleteVPCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVPCRequest.ProtoReflect.Descriptor instead.
func (*DeleteVPCRequest) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteVPCRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DeleteVPCRequest) GetVpcId() string {
	if x != nil {
		return x.VpcId
	}
	return ""
}

type DeleteVPCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vpc           *VPC                   `protobuf:"bytes,1,opt,name=vpc,proto3" json:"vpc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteVPCResponse) Reset() {
	*x = DeleteVPCResponse{}
	mi := &file_network_v1_network_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteVPCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteVPCResponse) ProtoMessage() {}

func (x *DeleteVPCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteVPCResponse.ProtoReflect.Descriptor instead.
func (*DeleteVPCResponse) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteVPCResponse) GetVpc() *VPC {
	if x != nil {
		return x.Vpc
	}
	return nil
}

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_network_v1_network_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{11}
}

func (x *GetOperationRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *Operation             `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationResponse) Reset() {
	*x = GetOperationResponse{}
	mi := &file_network_v1_network_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationResponse) ProtoMessage() {}

func (x *GetOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationResponse.ProtoReflect.Descriptor instead.
func (*GetOperationResponse) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{12}
}

func (x *GetOperationResponse) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

var File_network_v1_network_proto protoreflect.FileDescriptor

const file_network_v1_network_proto_rawDesc = "" +
	"\n" +
	"\x18network/v1/network.proto\x12\n" +
	"network.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb5\x04\n" +
	"\x03VPC\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x12\n" +
	"\x04cidr\x18\x05 \x01(\tR\x04cidr\x12/\n" +
	"\x05state\x18\x06 \x01(\x0e2\x19.network.v1.ResourceStateR\x05state\x12\x16\n" +
	"\x06reason\x18\a \x01(\tR\x06reason\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x18\n" +
	"\aversion\x18\n" +
	" \x01(\x03R\aversion\x12;\n" +
	"\vobserved_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12+\n" +
	"\x11observation_stale\x18\f \x01(\bR\x10observationStale\x12*\n" +
	"\x11last_operation_id\x18\r \x01(\tR\x0flastOperationId\x12!\n" +
	"\fsubnet_count\x18\x0e \x01(\x03R\vsubnetCount\x12%\n" +
	"\x0ereason_message\x18\x0f \x01(\tR\rreasonMessage\"\xb1\x04\n" +
	"\tOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12-\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x19.network.v1.OperationKindR\x04kind\x120\n" +
	"\x05state\x18\x05 \x01(\x0e2\x1a.network.v1.OperationStateR\x05state\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12=\n" +
	"\fcompleted_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\vcompletedAt\x12B\n" +
	"\x0fnext_attempt_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\rnextAttemptAt\x12=\n" +
	"\rresource_type\x18\v \x01(\x0e2\x18.network.v1.ResourceTypeR\fresourceType\x12%\n" +
	"\x0ereason_message\x18\f \x01(\tR\rreasonMessage\"o\n" +
	"\vAttribution\x12\x14\n" +
	"\x05actor\x18\x01 \x01(\tR\x05actor\x12#\n" +
	"\rdirect_caller\x18\x02 \x01(\tR\fdirectCaller\x12%\n" +
	"\x0ecorrelation_id\x18\x03 \x01(\tR\rcorrelationId\"\xdd\x01\n" +
	"\x10CreateVPCRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04cidr\x18\x03 \x01(\tR\x04cidr\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\x129\n" +
	"\vattribution\x18\x06 \x01(\v2\x17.network.v1.AttributionR\vattribution\"6\n" +
	"\x11CreateVPCResponse\x12!\n" +
	"\x03vpc\x18\x01 \x01(\v2\x0f.network.v1.VPCR\x03vpc\"C\n" +
	"\rGetVPCRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06vpc_id\x18\x02 \x01(\tR\x05vpcId\"3\n" +
	"\x0eGetVPCResponse\x12!\n" +
	"\x03vpc\x18\x01 \x01(\v2\x0f.network.v1.VPCR\x03vpc\"\xa1\x01\n" +
	"\x0fListVPCsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12/\n" +
	"\x05state\x18\x03 \x01(\x0e2\x19.network.v1.ResourceStateR\x05state\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x05 \x01(\tR\x06cursor\"Z\n" +
	"\x10ListVPCsResponse\x12%\n" +
	"\x05items\x18\x01 \x03(\v2\x0f.network.v1.VPCR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"F\n" +
	"\x10DeleteVPCRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06vpc_id\x18\x02 \x01(\tR\x05vpcId\"6\n" +
	"\x11DeleteVPCResponse\x12!\n" +
	"\x03vpc\x18\x01 \x01(\v2\x0f.network.v1.VPCR\x03vpc\"U\n" +
	"\x13GetOperationRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\"K\n" +
	"\x14GetOperationResponse\x123\n" +
	"\toperation\x18\x01 \x01(\v2\x15.network.v1.OperationR\toperation*\xdf\x01\n" +
	"\rResourceState\x12\x1e\n" +
	"\x1aRESOURCE_STATE_UNSPECIFIED\x10\x00\x12\x1f\n" +
	"\x1bRESOURCE_STATE_PROVISIONING\x10\x01\x12\x1c\n" +
	"\x18RESOURCE_STATE_AVAILABLE\x10\x02\x12\x1b\n" +
	"\x17RESOURCE_STATE_DEGRADED\x10\x03\x12\x19\n" +
	"\x15RESOURCE_STATE_FAILED\x10\x04\x12\x1b\n" +
	"\x17RESOURCE_STATE_DELETING\x10\x05\x12\x1a\n" +
	"\x16RESOURCE_STATE_DELETED\x10\x06*\xe0\x01\n" +
	"\x0eOperationState\x12\x1f\n" +
	"\x1bOPERATION_STATE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16OPERATION_STATE_QUEUED\x10\x01\x12\x1b\n" +
	"\x17OPERATION_STATE_RUNNING\x10\x02\x12\x1c\n" +
	"\x18OPERATION_STATE_RETRYING\x10\x03\x12\x1b\n" +
	"\x17OPERATION_STATE_BLOCKED\x10\x04\x12\x1d\n" +
	"\x19OPERATION_STATE_SUCCEEDED\x10\x05\x12\x1a\n" +
	"\x16OPERATION_STATE_FAILED\x10\x06*m\n" +
	"\rOperationKind\x12\x1e\n" +
	"\x1aOPERATION_KIND_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19OPERATION_KIND_CREATE_VPC\x10\x01\x12\x1d\n" +
	"\x19OPERATION_KIND_DELETE_VPC\x10\x02*D\n" +
	"\fResourceType\x12\x1d\n" +
	"\x19RESOURCE_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RESOURCE_TYPE_VPC\x10\x012\xff\x02\n" +
	"\x0eNetworkService\x12H\n" +
	"\tCreateVPC\x12\x1c.network.v1.CreateVPCRequest\x1a\x1d.network.v1.CreateVPCResponse\x12?\n" +
	"\x06GetVPC\x12\x19.network.v1.GetVPCRequest\x1a\x1a.network.v1.GetVPCResponse\x12E\n" +
	"\bListVPCs\x12\x1b.network.v1.ListVPCsRequest\x1a\x1c.network.v1.ListVPCsResponse\x12H\n" +
	"\tDeleteVPC\x12\x1c.network.v1.DeleteVPCRequest\x1a\x1d.network.v1.DeleteVPCResponse\x12Q\n" +
	"\fGetOperation\x12\x1f.network.v1.GetOperationRequest\x1a .network.v1.GetOperationResponseBGZEgithub.com/zhangzhe-ctrl/ani-network-service/api/network/v1;networkv1b\x06proto3"

var (
	file_network_v1_network_proto_rawDescOnce sync.Once
	file_network_v1_network_proto_rawDescData []byte
)

func file_network_v1_network_proto_rawDescGZIP() []byte {
	file_network_v1_network_proto_rawDescOnce.Do(func() {
		file_network_v1_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_v1_network_proto_rawDesc), len(file_network_v1_network_proto_rawDesc)))
	})
	return file_network_v1_network_proto_rawDescData
}

var file_network_v1_network_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_network_v1_network_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_network_v1_network_proto_goTypes = []any{
	(ResourceState)(0),            // 0: network.v1.ResourceState
	(OperationState)(0),           // 1: network.v1.OperationState
	(OperationKind)(0),            // 2: network.v1.OperationKind
	(ResourceType)(0),             // 3: network.v1.ResourceType
	(*VPC)(nil),                   // 4: network.v1.VPC
	(*Operation)(nil),             // 5: network.v1.Operation
	(*Attribution)(nil),           // 6: network.v1.Attribution
	(*CreateVPCRequest)(nil),      // 7: network.v1.CreateVPCRequest
	(*CreateVPCResponse)(nil),     // 8: network.v1.CreateVPCResponse
	(*GetVPCRequest)(nil),         // 9: network.v1.GetVPCRequest
	(*GetVPCResponse)(nil),        // 10: network.v1.GetVPCResponse
	(*ListVPCsRequest)(nil),       // 11: network.v1.ListVPCsRequest
	(*ListVPCsResponse)(nil),      // 12: network.v1.ListVPCsResponse
	(*DeleteVPCRequest)(nil),      // 13: network.v1.DeleteVPCRequest
	(*DeleteVPCResponse)(nil),     // 14: network.v1.DeleteVPCResponse
	(*GetOperationRequest)(nil),   // 15: network.v1.GetOperationRequest
	(*GetOperationResponse)(nil),  // 16: network.v1.GetOperationResponse
	(*timestamppb.Timestamp)(nil), // 17: google.protobuf.Timestamp
}
var file_network_v1_network_proto_depIdxs = []int32{
	0,  // 0: network.v1.VPC.state:type_name -> network.v1.ResourceState
	17, // 1: network.v1.VPC.created_at:type_name -> google.protobuf.Timestamp
	17, // 2: network.v1.VPC.updated_at:type_name -> google.protobuf.Timestamp
	17, // 3: network.v1.VPC.observed_at:type_name -> google.protobuf.Timestamp
	2,  // 4: network.v1.Operation.kind:type_name -> network.v1.OperationKind
	1,  // 5: network.v1.Operation.state:type_name -> network.v1.OperationState
	17, // 6: network.v1.Operation.created_at:type_name -> google.protobuf.Timestamp
	17, // 7: network.v1.Operation.updated_at:type_name -> google.protobuf.Timestamp
	17, // 8: network.v1.Operation.completed_at:type_name -> google.protobuf.Timestamp
	17, // 9: network.v1.Operation.next_attempt_at:type_name -> google.protobuf.Timestamp
	3,  // 10: network.v1.Operation.resource_type:type_name -> network.v1.ResourceType
	6,  // 11: network.v1.CreateVPCRequest.attribution:type_name -> network.v1.Attribution
	4,  // 12: network.v1.CreateVPCResponse.vpc:type_name -> network.v1.VPC
	4,  // 13: network.v1.GetVPCResponse.vpc:type_name -> network.v1.VPC
	0,  // 14: network.v1.ListVPCsRequest.state:type_name -> network.v1.ResourceState
	4,  // 15: network.v1.ListVPCsResponse.items:type_name -> network.v1.VPC
	4,  // 16: network.v1.DeleteVPCResponse.vpc:type_name -> network.v1.VPC
	5,  // 17: network.v1.GetOperationResponse.operation:type_name -> network.v1.Operation
	7,  // 18: network.v1.NetworkService.CreateVPC:input_type -> network.v1.CreateVPCRequest
	9,  // 19: network.v1.NetworkService.GetVPC:input_type -> network.v1.GetVPCRequest
	11, // 20: network.v1.NetworkService.ListVPCs:input_type -> network.v1.ListVPCsRequest
	13, // 21: network.v1.NetworkService.DeleteVPC:input_type -> network.v1.DeleteVPCRequest
	15, // 22: network.v1.NetworkService.GetOperation:input_type -> network.v1.GetOperationRequest
	8,  // 23: network.v1.NetworkService.CreateVPC:output_type -> network.v1.CreateVPCResponse
	10, // 24: network.v1.NetworkService.GetVPC:output_type -> network.v1.GetVPCResponse
	12, // 25: network.v1.NetworkService.ListVPCs:output_type -> network.v1.ListVPCsResponse
	14, // 26: network.v1.NetworkService.DeleteVPC:output_type -> network.v1.DeleteVPCResponse
	16, // 27: network.v1.NetworkService.GetOperation:output_type -> network.v1.GetOperationResponse
	23, // [23:28] is the sub-list for method output_type
	18, // [18:23] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_network_v1_network_proto_init() }
func file_network_v1_network_proto_init() {
	if File_network_v1_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_v1_network_proto_rawDesc), len(file_network_v1_network_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_v1_network_proto_goTypes,
		DependencyIndexes: file_network_v1_network_proto_depIdxs,
		EnumInfos:         file_network_v1_network_proto_enumTypes,
		MessageInfos:      file_network_v1_network_proto_msgTypes,
	}.Build()
	File_network_v1_network_proto = out.File
	file_network_v1_network_proto_goTypes = nil
	file_network_v1_network_proto_depIdxs = nil
}
